### ISSUE TITLE
Remove cvt_l_d instruction usage

### ISSUE THREAD

**Issue by kisg** [v8mips/v8mips#61] opened 2013-09-10 20:29 UTC
cvt_l_d and cvt_d_l instructions are unpredictable when executed in FR=0 FPU mode, which is the one currently used in V8. These instructions are not used anywhere in V8, except in the cctests.
We should remove the usage of these instructions.

There are 2 alternatives:
1. Only remove the cctest calls, and add checks/assertions in the simulator / assembler to fail if the instructions are used in FR=0 mode.
2. Remove all occurrences of the instructions. They can be re-added if ever needed.

We (Paul and I) are leaning towards option 2, but are open for suggestions, if anybody has new insights.

**Comment by palfia** [comment] 2014-02-07 19:16
Duplicate of #70.

**Closed as completed by palfia** 2014-02-07 19:16 UTC
