### ISSUE TITLE
Compilation failure: MIPS32R1 compilation error with clang

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#394] opened 2016-09-20 09:41 UTC
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang%2Cmipsr1%20-%20builder/builds/268/steps/compile/logs/stdio

**Comment by ilijapavlovic** [comment] 2016-09-26 06:23
The problem is solved with following CL: https://codereview.chromium.org/2359923003/
Landed as https://crrev.com/7d482781193653741fa2c2b0af6ece34734a4df2

**Closed as completed by ilijapavlovic** 2016-09-26 06:23 UTC
