### ISSUE TITLE
Bughunting: Sim - edge: mjsunit/regress/regress-int32-truncation

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#339] opened 2016-06-24 09:05 UTC
The test mjsunit/regress/regress-int32-truncation fails on simulator
TARGET_ARCH=mipsel
MODE=release
VARIANT=r2
Other details: https://v8.mips.com/bbv8/builders/Sim%20-%20edge/builds/11467/steps/Check/logs/regress-int32-truncat..

**Comment by palfia** [comment] 2016-06-24 09:08
Duplicate of #336.

**Closed as completed** 2016-06-24 09:11 UTC
