### ISSUE TITLE
Bughunting: unittests/ThreadTicks.ThreadNow on mipsr1

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#325] opened 2016-06-01 09:38 UTC
Fails on R1 in both release and debug mode: 

https://v8.mips.com/builders/Target%20-%20edge%20-%20mipsr1/builds/7142
https://v8.mips.com/builders/Target%20-%20Debug%20-%20edge%20-%20mipsr1/builds/628

**Comment by palfia** [comment] 2016-07-19 08:00
Fails because the broadcom kernel doesn't support the nanosec precision with CLOCK_THREAD_CPUTIME_ID (it has millisec precision), and thus the test fails, because it detects that no time elapsed since the beginning of the test.
Put this on hold for now.

**Comment by ibogosavljevic** [comment] 2018-06-08 09:26
* The test fails because of the low resolution of CLOCK_THREAD_CPUTIME_ID timer
* We modified the test to make sure this clock increases by at least one tick
* CL sent to review and landed: https://chromium-review.googlesource.com/c/v8/v8/+/1082352
* Issue doesn't reproduce on the buildbot anymore

**Closed as completed by ibogosavljevic** 2018-06-08 09:26 UTC
Labels: on-hold, build-failure
