### ISSUE TITLE
Implement missing tests for bit-conversion macro-asm instructions

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#254] opened 2016-02-18 22:38 UTC
Some bit-conversion macro-asm instruction does not have a corresponding test in test-macro-asm. Please implement these tests in test-macro-assembler-mips*.cc.

I'm sure these instructions don't have a test, but if you find more, implement those as well:
Cvt_d_ul
Cvt_s_uw
Trunc_ul_d
Trunc_ul_s
Trunc_uw_s

**Comment by ilijapavlovic** [comment] 2016-02-19 13:00
Following instructions also have not implemented tests:
Cvt_s_ul
Trunc_w_d
Trunc_l_d
Trunc_l_ud

**Comment by ilijapavlovic** [comment] 2016-02-22 12:20
CL ready for review: https://codereview.chromium.org/1719893002/
Implemented tests for Cvt_s_uw, Cvt_s_ul, Cvt_d_ul.

**Comment by ilijapavlovic** [comment] 2016-02-29 12:00
On previous link, something was not done correctly with CL upload. Here is the new link for review:
https://codereview.chromium.org/1747863002/

**Comment by ilijapavlovic** [comment] 2016-03-04 08:05
Uploaded new CL according comments and recommendations: https://codereview.chromium.org/1747863002/

**Comment by ilijapavlovic** [comment] 2016-03-09 13:09
Landed as https://crrev.com/b29846c283e7fed774d633bb78bb3677d0b45fa8

**Comment by palfia** [comment] 2016-03-10 00:46
It seems there's at least one test failure in R6 mode under qemu: https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/2393/steps/Check/logs/Cvt_s_uw_Trunc_uw_s

I'm not sure if it's a qemu-related failure or a real failure. I think it would be a good idea to execute these tests on a hw board.

**Comment by ilijapavlovic** [comment] 2016-03-11 10:49
On the FPGA board this problem was not possible to reproduce.

**Comment by ilijapavlovic** [comment] 2016-03-11 13:42
Here is the code for the test:

```
  __ Cvt_s_uw(f0, a0);
  __ Trunc_uw_s(f2, f0, f1);
  __ dmfc1(v0, f2);
  __ jr(ra);
  __ nop();
```

Here is problematical sample for the qemu:

```
input   = 0000000000 
expected = 0.000000 
received = 0xffffffff00000000
```

When previous sample is executed on FPGA, we got following output:

```
  input   = 0000000000 
 expected = 0.000000 
 received = 000000000000000000  
```

If a 32-bit data are stored in a 64-bit register, than bit 31 should be copied in all bits from 32 - 63.
In the qemu, this is not the case, and we can say (or state) that this is a problem in the qemu.

This problem can ba bypassed if f2 register is set on 0 on the beginning of the test code:

```
  __ dmtc1(zero_reg, f2);
  __ Cvt_s_uw(f0, a0);
  __ Trunc_uw_s(f2, f0, f1);
  __ dmfc1(v0, f2);
  __ jr(ra);
  __ nop();
```

With this, the test will be also successful on the qemu.

**Comment by ilijapavlovic** [comment] 2016-03-14 10:52
Another root of the problem is using `mtc1` instruction in implementations of following instructions:

```
Trunc_uw_d
Trunc_uw_s
Trunc_ul_s
```

For `mtc1` instruction is specified following:

> "The low word in GPR rt is placed into the low word of FPR fs. If FPRs are 64 bits wide, bits 63..32 of FPR fs become UNPREDICTABLE."

The `mtc1` instruction should be followed by `mthc1` instruction which should set bits 63..32 on zero:
`mthc1(zero_reg, fd)`.

FPR register which is initialized only with `mtc1` instruction, can have higher word with some random value, and this can be potential problem if all 64-bits of the FPR are used later.

**Comment by ilijapavlovic** [comment] 2016-03-18 12:14
Uploaded CL which fixes the test: https://codereview.chromium.org/1812193003/

**Comment by ilijapavlovic** [comment] 2016-03-18 13:36
Landed as https://crrev.com/a4e5d1541a10b4d4da8dc33250cb75df2c43154f

**Closed as completed** 2016-03-21 08:17 UTC
