### ISSUE TITLE
Qemu r6 failure: mjsunit/regress/regress-944

### ISSUE THREAD

**Issue by djpesic** [v8mips/v8mips#187] opened 2015-09-17 08:03 UTC
Test mjsunit/regress/regress-944 fails on mips32r6, debug mode with:
mjsunit/regress/regress-944

```
Fatal error in ../src/code-stubs.cc, line 506
Check failed: from != to.
```

**Comment by ibogosavljevic** [comment] 2015-11-16 14:35
This issue is same as issue #177. The failure is due to qemu bug. It doesn't reproduce neither on board nor simulator. The patch from the issue #177 removes it. 
Reported to Imagination team which works supports MIPS QEMU, issue tracker id 2022
Closing issue as duplicate of #177.

**Closed as completed by ibogosavljevic** 2015-11-16 14:35 UTC
