### ISSUE TITLE
Debug mode fails on softfloat builds, related to snapshots.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#33] opened 2013-04-05 02:56 UTC
When I built for soft float (using sim) to test the recent fixes, I got a lot of errors in the debug build. In snapshot mode, just about every test failed. 

It is possible that my build procedure is bad, I just did this:

```
export GYPFLAGS="-Dv8_use_mips_abi_hardfloat=false -Dv8_can_use_fpu_instructions=false"
make mipsel.debug.check [snapshot=off] -j24
```

I was using today's google bleeding edge, with Dusan's softfloat fix cherry-picked.
The failure was always for this ASSERT:

```
# Fatal error in ../src/assembler.cc, line 189
# CHECK(CpuFeatures::IsSafeForSnapshot(f)) failed
```

When I disabled snapshots, most tests would pass, I got 30 failures, they were all in cctest/test-serialize.

If this is not a build procedure problem, then it's an issue of crankshaft expecting FPU, when compiling the code-stubs. Please take a look at the backtrace leading to this ASSERT fail:

```
 1: V8_Fatal
 2: v8::internal::CpuFeatureScope::CpuFeatureScope(v8::internal::AssemblerBase*, v8::internal::CpuFeature)
 3: v8::internal::LCodeGen::GenerateCode()
 4: v8::internal::LChunk::Codegen(v8::internal::Code::Kind)
 5: ??
 6: v8::internal::KeyedLoadFastElementStub::GenerateCode()
 7: v8::internal::CodeStub::GetCode(v8::internal::Isolate*)
 8: v8::internal::KeyedLoadStubCompiler::CompileLoadElement(v8::internal::Handle<v8::internal::Map>)
 9: v8::internal::StubCache::ComputeKeyedLoadElement(v8::internal::Handle<v8::internal::Map>)
10: v8::internal::KeyedLoadIC::LoadElementStub(v8::internal::Handle<v8::internal::JSObject>)
11: v8::internal::KeyedLoadIC::Load(v8::internal::InlineCacheState, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::ICMissMode)
12: v8::internal::KeyedLoadIC_Miss(v8::internal::Arguments, v8::internal::Isolate*)
13: v8::internal::Simulator::SoftwareInterrupt(v8::internal::Instruction*)
14: v8::internal::Simulator::DecodeTypeRegister(v8::internal::Instruction*)
15: v8::internal::Simulator::InstructionDecode(v8::internal::Instruction*)
16: v8::internal::Simulator::Execute()
```

LCodeGen::GenerateCode is definitely setting up a CpuFeatreuScope with FPU required.

**Comment by paul99** [comment] 2013-04-05 03:08
OK, LCodeGen::GenerateCode having a CpuFeatureScope scope(masm(), FPU) is definitely a problem.

The equivalent for ARM was removed in cd9236c59ece6fb717712251dd8fe46f9a89c772 (13236) Re-land Crankshaft-generated KeyedLoad stubs. But that change was missed in our port of that change (66c13c77d1d88e371828c9444601fc9b0818d9e1)

However, fixing that is not quite sufficient, as I am still getting some debug failures now with this:

```
# Fatal error in ../src/mips/assembler-mips.cc, line 955
# CHECK(IsEnabled(FPU)) failed
```

We're generating an 'ldc1' here.

```
 1: V8_Fatal
 2: v8::internal::Assembler::GenInstrImmediate(v8::internal::Opcode, v8::internal::Register, v8::internal::FPURegister, int)
 3: v8::internal::Assembler::ldc1(v8::internal::FPURegister, v8::internal::MemOperand const&)
 4: v8::internal::LCodeGen::DoDeferredTaggedToI(v8::internal::LTaggedToI*)
 5: ??
 6: v8::internal::LCodeGen::GenerateDeferredCode()
 7: v8::internal::LCodeGen::GenerateCode()
 8: v8::internal::LChunk::Codegen(v8::internal::Code::Kind)
 9: v8::internal::OptimizingCompiler::GenerateAndInstallCode()
10: ??
11: ??
12: ??
13: v8::internal::Compiler::CompileLazy(v8::internal::CompilationInfo*)
14: ??
15: v8::internal::Compiler::CompileLazy(v8::internal::CompilationInfo*)
16: ??
17: v8::internal::JSFunction::CompileLazy(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::ClearExceptionFlag)
18: v8::internal::CallIC_Miss(v8::internal::Arguments, v8::internal::Isolate*)
19: v8::internal::Simulator::SoftwareInterrupt(v8::internal::Instruction*)
20: v8::internal::Simulator::DecodeTypeRegister(v8::internal::Instruction*)
21: v8::internal::Simulator::InstructionDecode(v8::internal::Instruction*)
22: v8::internal::Simulator::Execute()
```

Ákos, can you take a look at this? Dusan, if you have thoughts, or a fix, please let us know as well.

**Comment by dusmil** [comment] 2013-04-05 11:16
The fix for this is trivial. Paul is right, FPU check that causing the problem in GenerateCode (lithium-mips-codegen.cc) is removed in cd9236c. We should remove it, too.

@paul99 
Regarding the "ldc1" appearance, I think you did not build for soft-float correctly for simulator, there is a missing piece. It is important to set enable_fpu flag to false in flag_definitions.h. Otherwise, FPU will be enabled  when running on simulator.

The fix is submitted and pushed to dm-dev.

**Comment by paul99** [comment] 2013-04-05 13:57
Can you be more specific about this: "It is important to set enable_fpu flag to false in flag_definitions.h"?

Do you mean changing this via cmd line switch, or literally editing the file? 

Can we not handle this correctly via a change to simulator.cc,h since the softfloat flags are known at compile time?

Does it make sense to include such a change in the CL you just uploaded?

**Comment by dusmil** [comment] 2013-04-05 15:03
Yes, I usually edit flag-definitions.h  and set enable-fpu to false. But, there is option to externally set it to false when running d8 shell on simulator.  You can do this via command line when run shell as:  ./out/mipsel.release/d8  --noenable-fpu. The problem is that I have not figured out how to pass that flag yet, when I run the tests through run-test.py script, and when I set it in flag-definition.h file I am certain that FPU is not present in simulator.

**Comment by paul99** [comment] 2013-04-05 15:13
My related question is since we have the "-Dv8_use_mips_abi_hardfloat=false -Dv8_can_use_fpu_instructions=false" on the compiler command line, can we not override this setting (somehow) within simulator.cc. 

I don't want to put funny conditional compiles in flag-definitions.h, of course, but if we can hide that ugliness in the mips simulator, then it could be a good solution.

Or we can look further at passing flags thru run-tests.py. If there is not a way, there should be, and we could propose a patch.

**Comment by dusmil** [comment] 2013-04-05 16:29
I understand your point, but this flag enable_fpu  is runtime flag  that has higher priority than others build flags when simulator is used, and the reason is debug purposes. For instance you can compile v8 for soft float and suddenly you want to turn on FPU unit on simulator in d8 shell to debug something. The same applies for ARM. 

Don`t forget that we support in v8  soft_float ( this implies ABI selection more than is FPU instruction is generated) with FPU on. This means we generated FPU code, we have crankshaft but we call runtime routines in C through soft-float ABI.

I think I need to investigate the run-test.py script for passing flags to d8,  and I am doing it now.
I am convinced there is a way to deal with this through script, otherwise we will make a patch in Mips part of code for this.

**Comment by dusmil** [comment] 2013-04-05 17:10
I know now, the magic option is --extra-flags "--noenable_fpu", this should be added in line for running tests.
For example:

 tools/run-tests.py -j6 --arch=mipsel --mode=debug --timeout=240 --verbose --time --no-presubmit --extra-flags "--noenable_fpu" --report mjsunit | tee test.log

Just as note, this "--noenable-fpu"  flag has effect only on simulator, on HW it is ignored.

**Comment by paul99** [comment] 2013-04-06 01:26
Still is failing for me with the execution of a ldc1. About half of all tests fail running your command:

```
make clean
export GYPFLAGS="-Dv8_use_mips_abi_hardfloat=false -Dv8_can_use_fpu_instructions=false"
make mipsel.debug -j24
tools/run-tests.py -j6 --arch=mipsel --mode=debug --timeout=240 --verbose --time --no-presubmit --extra-flags "--noenable_fpu" --report mjsunit
```

Here it as after running a few tests:

```
[00:15|%   2|+  41|-  33]:  mjsunit/apply# 
```

I was hoping to debug this further today, but ran out of time.

**Comment by dusmil** [comment] 2013-04-06 15:34
I realize now why I do not see errors. Probably, you do the testing on top of bleeding_edge  either from google repo or our github, and I used branch that is not up to date from Monday. In the meantime new commit "8fd9594" is landed which add new stub compiled by crankshaft. This one will give us headache as I can see. It is FastCloneShallowArrayStub that uses other lithium operations/instructions (KeyedStores) that do not have soft float code paths. Even for Arm they do not exist.That is why you probably see the ldc1. 

It look like Google developers  forgot or do not care about soft-float suddenly, although other stubs generated by crankshaft have soft-float code paths. I do not think we could not solve this, but it requires an bigger effort. Also, I want to point in what moment this is landed and how bad luck we have, it happened immediately after  soft-float support for MIPS is fixed.

Could, you please paste the some of the errors you have got in testing, just to be sure we see the same problem?

**Comment by paul99** [comment] 2013-04-06 18:13
Your're right, of course, Dusan, nice analysis. I grabbed 491a4702fed697124238902be9ac13c3f163fc35 and cherry picked your two changes: dc0d1cafa178404c0f38868ccf81b07fcbc63f00 and 9fce149bebb8bd93066306d023b223937daa7263 (these commit IDs from google bleeding_edge), and it runs the tests fine.

I will ping Danno and Michael S. about this. Danno had claimed they would support soft float thru 3.17, which we are still working on.

**Comment by paul99** [comment] 2013-04-08 18:54
(from out-of-band email, the google trunk is now the staging area for what will go soon to 3.17 branch.)

Dusan, can you review the current google trunk, and determine which of your recent softfloat fixes need to be added there? Certainly the last two do, but I am wondering about the ones before that.

Please update that here, ask Ákos will likely be doing a merge soon of all the mips patches that need to be there.

**Comment by dusmil** [comment] 2013-04-09 14:37
After I examined google trunk, I determined that only last two soft-float fixes needs to be added, the rest of them is already there.

**Comment by paul99** [comment] 2013-04-09 14:43
Per email just sent, the the trunk will not be used for 3.17, but rather the existing 3.17 branch, at 3.17.6.

Please re-evaluate the necessary patches.

**Comment by paul99** [comment] 2013-04-09 15:22
This is not necessarily the best place to document this, but here is the working list I have:

Ákos' previous merge (not landed) for 3.17.6 had r13798, r13802, r13803, r13804, r13805. 
The clang patch is r14100
the /proc/cpuinfo logging is 14170   (however I don't think ulan's original made it in there at 3.17.6, so this may not be important.)

I see these for softfloat: r14099, r14101,  r14145, r14158   -- are there any more?

**Comment by palfia** [comment] 2013-04-09 23:10
Hi guys,

It seems, that the fix in commit r14158 introduces a lot of test failures in hardfloat debug mode on bleeding_edge. I didn't have enough time to investigate it deeply, but I created a quick fix for this:

https://github.com/paul99/v8m-rb/commit/e47f048fc7c00da169f26e360c874006b47e7839

This fix is only tested in hardfloat mode, I have not tested it in softfloat mode yet, it's too late to do this today. :)

Could you please also take a look at this?

**Comment by paul99** [comment] 2013-04-10 03:17
Dusan, can you please test out this fix from Ákos in softfloat as early as possible, and update the issue? My prelim testing in hardfloat made it seem fine, and the changes certainly look like they'd not hurt softtfloat mode. 

As I said i the code-review on that fix (https://github.com/paul99/v8m-rb/commit/e47f048fc7c00da169f26e360c874006b47e7839) we should submit this to google asap,  if we think we can't do the real softfloat removal port within a day or so. Ákos can do the CL once you approve it with softfloat testing.

One other note related to the softfloat removal port: the longer that takes us, the more risk we have of google landing some new crankshaft commit that won't work for mips, without lots of hacking.

So let's push this in as a stopgap, but try to get the softfloat removal done within a day or two.

**Comment by kisg** [comment] 2013-04-10 08:32
It looks like the Google guys saw this failure as well, and pushed it for us: https://codereview.chromium.org/14030002/

Should we thank them on the issue? I don't no what is the proper etiquette in this case.

**Comment by dusmil** [comment] 2013-04-10 09:06
Very nice,  missing FPU scopes in lithium instructions required for hard-float this time, spotted and fixed by them.

**Comment by paul99** [comment] 2013-04-10 15:05
Gergely, very good idea to thank Sven for this change. I will do that today via direct email.

**Comment by kisg** [comment] 2014-11-11 16:11
Fixed.

**Closed as completed by kisg** 2014-11-11 16:11 UTC
