### ISSUE TITLE
Fix cctest/test-types/Is2_heap on clang mips64 target build.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#191] opened 2015-09-22 04:46 UTC
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/121/steps/Check/logs/Is2_heap

Note that this build (https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/121) has check fails on TestSizeOfRegExpCode which is expected, and also on movz_movn, which is covered in mips32 clang issue https://github.com/paul99/v8m-rb/issues/189

**Comment by ilijapavlovic** [comment] 2015-10-12 09:32
Test `cctest/test-types/Is2_heap` finishes with the message `Segmentation fault`.
The test is performed with GDB and following output was visible at the end:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000001205f62d4 in v8::internal::IsMinusZero (value=<optimized out>) at .././src/conversions.h:152
152 .././src/conversions.h: No such file or directory.
```

When the test is disassembled, following lines are noted as important:

```
   ...
   0x00000001205f6104 <+2652>:  sw  v1,56(sp)   // v1=0x122773f40; 56(sp)=0x22773f40
   ...
   0x00000001205f62d0 <+3112>:  lw  at,56(sp)   // at=0x22773f40
=> 0x00000001205f62d4 <+3116>:  ll  v1,0(at)    // <-- SIGSEGV; Segmentation fault
   ...
```

At the end of lines are register values and values stored in the memory location.
The problem is that double word value is stored as single word.

The same problem is described in [#190](https://github.com/paul99/v8m-rb/issues/190).

**Comment by ibogosavljevic** [comment] 2015-10-13 13:15
The same [patch to CLANG](http://reviews.llvm.org/D13649) which fixed the issue in #190 also fixes this issue. Again, we just need to wait until the patch is commited and Google guys update dependencies in v8

**Comment by ibogosavljevic** [comment] 2015-10-30 14:34
Patch for CLANG landed in http://reviews.llvm.org/rL251629. We expect to see the tests passing soon

**Comment by ibogosavljevic** [comment] 2015-12-01 09:42
Patch for CLANG landed in v8, closing the issue
https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/447/steps/Check/logs/stdio

**Closed as completed by ibogosavljevic** 2015-12-01 09:42 UTC
Labels: pri2
