### ISSUE TITLE
Bughunting: A few test from test-serialize suite fail on MIPSR6 

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#542] opened 2017-11-16 10:17 UTC
https://v8.imgtec.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20mipsr6%2Cunder%20qemu%2Cquick/builds/1914/steps/Check/logs/PartialSerializerCont..

**Comment by ilijapavlovic** [comment] 2017-11-17 07:01
The same test
 `cctest/test-serialize/PartialSerializerContext`
fails also for MIPS64 little endian r2 in release mode which is build with Clang.
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/3211/steps/Check/logs/stdio

The test also fails on following builders for r6:

- https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/1140/steps/Check/logs/stdio
- https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/874/steps/Check/logs/stdio

This error message is for mips64el.Release.r2:
```
=== cctest/test-serialize/PartialSerializerContext ===
--- stderr ---
Received signal 11 SEGV_MAPERR 00016224ba98

==== C stack trace ===============================

 [0x000121380d9c]
[end of stack trace]
Command: /bbv8-slaves/erpro8-board-8/build/slave/v8-linux-mips64el-target-edge-clang/build/v8/out/Release/cctest --random-seed=1475987250 test-serialize/PartialSerializerContext --nohard-abort
exit code: -11
```
This is error message for mipsel.debug.r6 from Qemu:
```
=== cctest/test-serialize/PartialSerializerContext ===
--- stderr ---
Received signal 4 <unknown> 000046c4249e

==== C stack trace ===============================

 [0x000001b1f694]
[end of stack trace]
qemu: uncaught target signal 4 (Illegal instruction) - core dumped
Command: /mips/tools/mips/swpkgs/bin/qemu-mipsel-V8-mipsr6-upstream-master-a008535b-with-upstream-patch -cpu mips32r6-generic /bbv8-slaves/mips-sim-6/build/slave/v8-linux-mipsel-debug-target-edge-clang-mipsr6-under-qemu/build/v8/out/Debug/cctest --random-seed=810888615 test-serialize/PartialSerializerContext --nohard-abort --enable-slow-asserts --verify-heap
exit code: -4
--- CRASHED ---
```

**Comment by ilijapavlovic** [comment] 2017-11-20 10:26
This CL causes that the test fails with time-out:
```
commit 0a346fc2645ba3cd02c0e85647fb6f4623c5bd00 (HEAD)
Author: Michael Achenbach <machenbach@chromium.org>
Date:   Fri Sep 29 10:19:29 2017 +0200

    Reland "[build] Switch windows default compilation to MSVS 2017"
    
```
This CL introduces new Clang version: `313786-1...`
Previous Clang version: `312679-1`
See https://github.com/v8mips/v8mips/issues/530

**Comment by ilijapavlovic** [comment] 2017-11-20 12:07
With this CL, the test started to crash:
```
1560988249c97c5cc1763aa364a0423f9e318c13
[bigint] Support BigInts in <<,>>,>>>,&,|,^ binary ops
Reviewed-on: https://chromium-review.googlesource.com/699424
```
If this test is executed in Debug mode, following error message is received:
```
=== cctest/test-serialize/PartialSerializerContext ===                    
#
# Fatal error in ../../src/compiler/register-allocator-verifier.cc, line 42
# Check failed: Immediately after CommitAssignmentPhase..
#
```
This is the same error message as in https://github.com/v8mips/v8mips/issues/530

**Comment by ilijapavlovic** [comment] 2017-11-20 12:37
Previous observations are for V8 build with Clang.

**Comment by ilijapavlovic** [comment] 2017-11-20 12:47
For mipsel.Debug.r6 the test fails with following error message:
```
=== cctest/test-serialize/PartialSerializerContext ===
--- stderr ---
#
# Fatal error in ../../src/mips/assembler-mips.cc, line 3857
# unreachable code
#

==== C stack trace ===============================

    /bbv8-slaves/mips-sim-12/build/slave/v8-linux-mipsel-debug-target-edge-mipsr6-under-qemu-quick/build/v8/out/Debug/cctest() [0x19a6798]
Received signal 6
qemu: uncaught target signal 6 (Aborted) - core dumped
Command: /mips/tools/mips/swpkgs/bin/qemu-mipsel-V8-mipsr6-upstream-master-a008535b-with-upstream-patch -cpu mips32r6-generic /bbv8-slaves/mips-sim-12/build/slave/v8-linux-mipsel-debug-target-edge-mipsr6-under-qemu-quick/build/v8/out/Debug/cctest --random-seed=-1629082040 test-serialize/PartialSerializerContext --nohard-abort --enable-slow-asserts --verify-heap
```

**Comment by ilijapavlovic** [comment] 2017-11-21 14:16
The CL which causes the test to fail:
```
fe916cd224a5bf8cbf1e8503a192c27fdbcda9f7 
MIPS: Use JIC/JIALC offset when possible
Review-Url: https://codereview.chromium.org/2542403002
```

**Comment by ilijapavlovic** [comment] 2017-11-24 06:47
```
Address Assembler::target_address_at(Address pc) {
  Instr instr1 = instr_at(pc);
  Instr instr2 = instr_at(pc + kInstrSize);
  // Interpret 2 instructions generated by li (lui/ori) or optimized pairs
  // lui/jic, aui/jic or lui/jialc.
  if (IsLui(instr1)) {
    if (IsOri(instr2)) {
      // Assemble the 32 bit value.
      return reinterpret_cast<Address>((GetImmediate16(instr1) << kLuiShift) |
                                       GetImmediate16(instr2));
    } else if (IsJicOrJialc(instr2)) {
      // Assemble the 32 bit value.
      return reinterpret_cast<Address>(CreateTargetAddress(instr1, instr2));
    }
  }

  // We should never get here, force a bad address if we do.
  UNREACHABLE();      // <--------------------------
}
```
Detected problematical instructions:
```
instr1=0x3c1900d9      => lui t9, 0xd9
instr2=0x33a10007      => andi at, sp, 0x7
instr3=0xd8200001      => beqzc at, 1
```

1. Instruction `ANDI` is not considered as possible the 2nd instruction.
2. Instruction `ANDI` uses register `sp` as one of operands - not `t9` which is used in `LUI`.

**Comment by ilijapavlovic** [comment] 2017-11-30 14:21
Instruction sequence `lui/andi/beqzc` is generated in following part of the code:
```
// ./src/mips/macro-assembler.cc

void TurboAssembler::CallCFunction(ExternalReference function,
                                   int num_reg_arguments,
                                   int num_double_arguments) {
  if (IsMipsArchVariant(kMips32r6)) {
    uint32_t lui_offset, jialc_offset;
    UnpackTargetAddressUnsigned(Operand(function).immediate(), lui_offset,
                                jialc_offset);
    ...
    lui(t9, lui_offset);          // <---  lui t9, 0xd9
    CallCFunctionHelper(t9, jialc_offset, num_reg_arguments,
                        num_double_arguments);
  } else {
    li(t9, Operand(function));
    CallCFunctionHelper(t9, 0, num_reg_arguments, num_double_arguments);
  }
}

void TurboAssembler::CallCFunctionHelper(Register function_base,
                                         int16_t function_offset,
                                         int num_reg_arguments,
                                         int num_double_arguments) {
  ...
#if V8_HOST_ARCH_MIPS
  if (emit_debug_code()) {
    int frame_alignment = base::OS::ActivationFrameAlignment();
    int frame_alignment_mask = frame_alignment - 1;
    // frame_alignment = 8; frame_alignment_mask = 7; kPoniterSize = 4 
    //     (frame_alignment > kPointerSize) ? 1 
    if (frame_alignment > kPointerSize) {
      DCHECK(base::bits::IsPowerOfTwo(frame_alignment));
      Label alignment_as_expected;
      UseScratchRegisterScope temps(this);
      Register scratch = temps.Acquire();
      And(scratch, sp, Operand(frame_alignment_mask));             // <---  andi at, sp, 0x7
      Branch(&alignment_as_expected, eq, scratch, Operand(zero_reg));   // <---  beqzc at, 1
      // Don't use Check here, as it will call Runtime_Abort possibly
      // re-entering here.
      stop("Unexpected alignment in CallCFunction");
      bind(&alignment_as_expected);
    }
  }
#endif  // V8_HOST_ARCH_MIPS
  ...
}
```
If emitting debug code is removed/deleted (no `andi/beqzc` instruction sequence) the test will be successful.

**Comment by ilijapavlovic** [comment] 2017-12-08 11:15
The problem is fixed with following CL:
```
commit f119c097697c0b1767111ff2d3e1f67779d8eba1
    MIPSR6: Load full address to t9 when calling PIC code
        
    Reviewed-on: https://chromium-review.googlesource.com/806494
```
The test is successful again.

**Closed as completed by ilijapavlovic** 2017-12-08 11:15 UTC
