### ISSUE TITLE
Bughunting: cctest/test-run-machops/RunFloat64MulAndFloat64Sub1

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#272] opened 2016-03-10 00:28 UTC
There's a test failure in R6 mode under qemu: cctest/test-run-machops/RunFloat64MulAndFloat64Sub1

https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr1/builds/6543

Please look into this failure.

You can find some infos about building in R6 mode and running under qemu: https://github.com/v8mips/v8mips/wiki/Running-tests-with-qemu-user-mode-for-R6
However, I'm not sure the infos written there are up-to-date.

@ibogosavljevic: Can you help Marija with creating an R6-qemu env?

**Comment by marijantic** [comment] 2016-03-16 13:32
Log file here (link above is not for R6 under qemu): https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20mipsr6%2Cunder%20qemu/builds/2427/steps/Check/logs/RunFloat64MulAndFloat..

**Comment by marijantic** [comment] 2016-03-16 16:00
Error message:

 Fatal error in .././test/cctest/compiler/value-helper.h, line 334
 Check failed: x == y (4.29497e+75 vs. 4.29497e+75).

**Comment by marijantic** [comment] 2016-03-17 09:31
This bug is a duplicate of #208

**Closed as completed by marijantic** 2016-03-17 09:31 UTC
