### ISSUE TITLE
Bughunting: mjsunit/regress/wasm/regress-827806 fails on MIPS64R6

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#644] opened 2018-06-05 08:49 UTC
Link to failure on buildbot: https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/1585/steps/Check%20%28flakes%29/logs/regress-827806

**Comment by mkaric** [comment] 2018-06-05 09:28
I could not reproduce the test failure. It has not failed since build 1585 in the link above. I'm putting this on hold to see if it starts failing again.

**Comment by mkaric** [comment] 2018-06-08 13:02
The test failed again on the last build:
https://v8.imgtec.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang%2Cmipsr6%2Cunder%20qemu/builds/1602

**Comment by mkaric** [comment] 2018-07-04 09:16
The build 1602 is the last time this test failed, now with over 40 builds without failing. I think we can close this issue.

**Closed as completed** 2018-07-04 09:16 UTC
Labels: r6, qemu
