### ISSUE TITLE
Optimization: Improve v8 MIPS according to instructions from MIPS ART team

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#478] opened 2017-04-24 12:00 UTC
We received e-mail some time ago from Alexey from ART team. They did some code revision and sent us their remarks. Please have a look at each of these remarks and see how it fits into our current framework:

Original mail content:
```
Ivica,

I was researching possible improvements in Android ART, which I'm
working on, and v8 code came up in one of my searches and I decided to
look at MIPS-specific bits in v8.

Here are a few findings from a shallow review of the existing code. I
don't know how v8 works, so these are mainly low level things.

MacroAssembler::Subu():
     incorrect operation when rt.imm32_ = 0xFFFF8000: adds 0xFFFF8000
instead of 0x00008000
     the same kind of problem exists in MIPS64's Subu() and Dsubu() as well

Assembler::LoadUpperOffsetForTwoMemoryAccesses():
     should test that both ((src.offset_ & kImm16Mask) + kIntSize) and
(src.offset_ & kImm16Mask) fit into int16_t
     additional improvements possible
     see Mips[64]Assembler::AdjustBaseAndOffset() in
aosp/art/compiler/optimizing/utils/mips[64]/assembler_mips[64].cc

MacroAssembler::AddPair(), MacroAssembler::SubPair():
     unnecessary instructions, can be done with just 4 without branches
     see InstructionCodeGeneratorMIPS::HandleBinaryOp() in
aosp/art/compiler/optimizing/code_generator_mips.cc

MacroAssembler::ShlPair(), MacroAssembler::ShrPair(),
MacroAssembler::SarPair():
     can be improved by using the ins instruction for shifts by constant
amounts and
     the code can be shortened for shifts by variable amount
     see InstructionCodeGeneratorMIPS::HandleShift() in
aosp/art/compiler/optimizing/code_generator_mips.cc
     (the trailing beqz+move+move can be changed to movn+movn on non-R6)

MacroAssembler::Neg_s(), MacroAssembler::Neg_d():
     and+and+or+xor can be replaced with lui(scratch2,
0x8000)+xor(scratch1, scratch1, scratch2)
     in MIPS64's Neg_d() can use daddiu(scratch2, zero,
1)+dsll32(scratch2, scratch2, 31)+xor(scratch1, scratch1, scratch2)

MacroAssembler::li():
     can probably be further improved for MIPS64, especially for MIPS64R6
     see TemplateLoadConst64() in
aosp/art/compiler/optimizing/utils/mips64/assembler_mips64.h

CodeGenerator::AssembleArchInstruction():
     case kMips[64]Ctz:
     case kMips64Dctz:
         can be done without branches
         see GenNumberOfTrailingZeroes() in
aosp/art/compiler/optimizing/intrinsics_mips[64].cc
     case kMips[64]Popcnt:
     case kMips64Dpopcnt:
         can be shorter and probably(?) faster
         see GenBitCount() in
aosp/art/compiler/optimizing/intrinsics_mips[64].cc

There's also code to compare and branch on <,<=,==,!=,>=,> and we're
trying to do it better:
InstructionCodeGeneratorMIPS::GenerateIntCompare(),
GenerateIntCompareAndBranch(),
GenerateLongCompareAndBranch(), GenerateLongCompare()
(https://android-review.googlesource.com/#/c/336744/)

IOW, you may benefit from some of the work done in ART.

Thanks,
Alexey
```

**Comment by mkaric** [comment] 2017-04-26 15:27
I confirmed the problem exists for the mentioned case in MacroAssembler::Subu() function. When imm value is int16 we emit addiu(x, y, -imm), but when imm is min_int16 (0xFFFF8000), then -imm = max_int16 + 1 so addiu cannot be used. I fixed this bug by checking is_int16(-imm), if not, we load imm to at register and then use subu(x, y, at) to subtract imm through at. This way for the case when imm = max_int16 + 1 (0x8000) we generate only one instruction. I also added the test for this in test-assembler-mips.cc and verified there are no more errors.

**Comment by mkaric** [comment] 2017-04-26 15:50
Then I noticed it is possible to add another optimization. Instead of loading imm value to at register and then subtracting at, we can also load -imm value and add it. This helps in cases such as imm = 0xFFFF7FFF where loading this value requires two instructions and another one for subtraction - lui, ori and subu. Instead we can load -imm value with just ori (-imm = 0x8001) and add it with addu, emiting one instruction less. Adjusted the code and the test to cover this case.

**Comment by mkaric** [comment] 2017-04-27 08:54
Created the CL: https://codereview.chromium.org/2845043002/
PTAL

**Comment by mkaric** [comment] 2017-04-28 12:18
The CL landed.

**Comment by mkaric** [comment] 2017-05-03 12:43
I implemented a large number of optimizations in MacroAssembler::li() for mips64 and added tests. However, some optimizations use DINSU instruction which is not yet implemented. I will add DINSM and DINSU instructions, and add tests for Dins macro assembler instruction. Also there may be more optimizations that could be added to li(), I will investigate.

**Comment by alexfru** [comment] 2017-05-04 03:50
One thing I had in mind w.r.t. dli is that the current code in TemplateLoadConst64() may generate 2 extra instructions for value than for -value or \~value, in which case it's better to load -value or \~value and then do dsubu or nor, saving one instruction. Other improvements should be possible as well.

**Comment by mkaric** [comment] 2017-05-08 16:47
@alexfru Yes, exactly, that will also be worth investigating. The optimization above for Subu is mips32 but for mips64 it will be more complex and will have to cover all li paths, so I will investigate when I get to that.

**Comment by mkaric** [comment] 2017-05-08 16:50
Uploaded the CL that adds DINSM and DINSU instructions and tests, also fixes other bit insertion and extraction instructions and adds missing tests. PTAL: https://codereview.chromium.org/2871663002/

**Comment by mkaric** [comment] 2017-05-10 10:19
Landed the CL that enables the use of DINSU instruction needed for some optimizations in li macro assembler instruction. I am also working on another optimization in li per comment by @alexfru above.

**Comment by mkaric** [comment] 2017-05-24 11:13
Landed the CL with li optimizations for mips64. Also added optimizations, fixes and tests for Subu and Dsubu, as well as other minor improvements: https://codereview.chromium.org/2892163002/.

**Comment by mkaric** [comment] 2017-05-24 11:46
@alexfru I think there is a problem with the following function in ART code. The condition ```IsInt<16>(value >> 16)``` will never be true when x == y because y has bits set so for values like 0x8000000080000000 that can be loaded using LUI + DINSU the function will return 3. I think there is no need to check if upper 16 bits in x are int16 either (if that was the original intention). I omitted the check in the CL I landed.
```
static inline int InstrCountForLoadReplicatedConst32(int64_t value) {
  int32_t x = Low32Bits(value);
  int32_t y = High32Bits(value);

  if (x == y) {
    return (IsUint<16>(x) || IsInt<16>(x) || ((x & 0xFFFF) == 0 && IsInt<16>(value >> 16))) ? 2 : 3;
  }

  return INT_MAX;
}
```

**Comment by alexfru** [comment] 2017-05-26 04:46
@mkaric You're right about lui+dinsu. I just found that I asked to remove the IsInt\<16\>() part it but it wasn't done (see this [change](https://android-review.googlesource.com/#/c/208442/1..2/compiler/utils/mips64/assembler_mips64.cc)) and everyone failed to see it. However, this should only miss the opportunity to emit a shorter instruction sequence. Thanks!

**Comment by mkaric** [comment] 2017-05-29 14:20
Uploaded a CL implementing new optimizations to li and Dsubu macros for mips64:
https://codereview.chromium.org/2909913002
PTAL.

**Comment by mkaric** [comment] 2017-06-20 10:02
The CL adding optimizations to li and Dsubu macro for mips64 landed.

**Comment by mkaric** [comment] 2017-06-29 13:44
Several CLs are uploaded, a CL that optimizes memory load/store helper, https://chromium-review.googlesource.com/c/552119/, a CL that optimizes Neg_s and Neg_d macro instructions, https://chromium-review.googlesource.com/c/555131/ and a CL that optimizes add, sub and shift pair macro instructions, https://chromium-review.googlesource.com/c/555513/. PTAL.

**Comment by alexfru** [comment] 2017-07-04 06:28
For MSA ld.df/st.df base/offset adjustment see Mips[64]Assembler::AdjustBaseOffsetAndElementSizeShift() and how it's used in https://android-review.googlesource.com/#/c/377753/ and https://android-review.googlesource.com/#/c/411424/.

**Comment by mkaric** [comment] 2017-07-07 09:32
The three CLs mentioned in my previous post all landed. Uploaded a new CL with optimizations to MipsCtz and MipsPopcnt in code generator for mips32 and mips64, https://chromium-review.googlesource.com/c/563197/.

**Comment by mkaric** [comment] 2017-07-11 08:48
The CL introducing optimizations in memory load/store helper, https://chromium-review.googlesource.com/c/552119/, caused several failures on r6 builders. The problem was in Sdc1 macro instruction where address in at register was overwritten before being used. Also in debug mode a DCHECK was failing because an incorrect type was used. This is fixed with a CL: https://chromium-review.googlesource.com/c/565297/.

**Comment by mkaric** [comment] 2017-07-12 10:21
The CL with optimizations to MipsCtz and MipsPopcnt in code generator for mips32 and mips64, https://chromium-review.googlesource.com/c/563197/, landed.

**Comment by mkaric** [comment] 2017-07-26 09:15
Uploaded the CL with compare instruction optimizations in code generator:
https://chromium-review.googlesource.com/c/584529/

**Comment by mkaric** [comment] 2017-07-26 09:22
@alexfru Thank you for your help with improvements in v8 code. As for base/offset adjustment for MSA, this is still work in progress in v8 and will be covered in a separate issue.

**Comment by mkaric** [comment] 2017-07-26 10:24
The CL with optimizations to compare in code generator landed. All optimizations listed above are now added, closing.

**Closed as completed by mkaric** 2017-07-26 10:24 UTC
