### ISSUE TITLE
Bughunting: Test execution cannot be started with patch for Clang.

### ISSUE THREAD

**Issue by ilijapavlovic** [v8mips/v8mips#334] opened 2016-06-13 12:13 UTC
Target architecture: mips64el
Mode: release
Variant: r6
Test platform: qemu user

The commit used for testing:

```
commit 5c22cf5ae7a7989669a363f783f9bd625bdacec5
Author: binji <binji@chromium.org>
Date:   Wed May 18 17:55:08 2016 -0700

    Add cmpxchg and lock instructions to x64 and ia32 {dis,}assemblers

    Review-Url: https://codereview.chromium.org/1986113004
    Cr-Commit-Position: refs/heads/master@{#36341}
```

Applied patch content:

```
diff --git a/src/base/atomicops_internals_mips64_gcc.h b/src/base/atomicops_internals_mips64_gcc.h
index 85b4e46..17eb39a 100644
--- a/src/base/atomicops_internals_mips64_gcc.h
+++ b/src/base/atomicops_internals_mips64_gcc.h
@@ -100,7 +100,7 @@ inline Atomic32 NoBarrier_AtomicIncrement(volatile Atomic32* ptr,
                        "beqz %1, 1b\n"  // start again on atomic error
                        "addu %1, %0, %3\n"  // temp2 = temp + increment
                        ".set pop\n"
-                       : "=&r" (temp), "=&r" (temp2), "=m" (*ptr)
+                       : "=&r" (temp), "=&r" (temp2), "=ZC" (*ptr)
                        : "Ir" (increment), "m" (*ptr)
                        : "memory");
   // temp2 now holds the final value.
@@ -237,7 +237,7 @@ inline Atomic64 NoBarrier_AtomicIncrement(volatile Atomic64* ptr,
                        "beqz %1, 1b\n"  // start again on atomic error
                        "daddu %1, %0, %3\n"  // temp2 = temp + increment
                        ".set pop\n"
-                       : "=&r" (temp), "=&r" (temp2), "=m" (*ptr)
+                       : "=&r" (temp), "=&r" (temp2), "=ZC" (*ptr)
                        : "Ir" (increment), "m" (*ptr)
                        : "memory");
   // temp2 now holds the final value.
```

Building v8 with Clang for mips64el.release.r6 was without exceptions or error messages, but execution of the test `cctest/*` was not possible.

```
cd <PROJECT>/v8
tools/run-tests.py -j6 --arch=mips64el --mode=release --extra-flags= --timeout=480 --verbose --time --no-presubmit --report 'cctest/*' '--command-prefix=<PROJECT>/simulators/cpu_I6400/bin/qemu-mips64el -R 2147483648 -cpu I6400'
Specifying --command-prefix disables network distribution, running tests locally.
>>> Running tests for mips64el.release
...
Corrupted startup resource '<PROJECT>/v8/out/mips64el.release/natives_blob.bin'.
Corrupted startup resource '<PROJECT>/v8/out/mips64el.release/snapshot_blob.bin'.


#
# Fatal error in ../test/cctest/test-debug.cc, line 4919
# Check failed: (N)==(num_blocked_).
#

==== C stack trace ===============================

qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped

Total: 0 tests
 *    0 tests will be skipped
 *    0 tests are expected to timeout sometimes
 *    0 tests are expected to be flaky but not crash
 *    0 tests are expected to pass
 *    0 tests are expected to fail that we won't fix
 *    0 tests are expected to fail that we should fix
Network distribution disabled, running tests locally.
Closing process pool.
Closing database connection.
[00:00|%   0|+   0|-   0]: Done 
```

Investigate what prevents the tests to be executed.

**Comment by ilijapavlovic** [comment] 2016-06-14 12:37
Used test for experimental purposes: `cctest/test-assembler-mips64/sub`

The test is started on port `1234` (this is the test in `debug` mode):

```
tools/run-tests.py -j6 --arch=mips64el --mode=debug --extra-flags= --timeout=480 --verbose --time --no-presubmit --report cctest/test-assembler-mips64/sub '--command-prefix=<PROJECT>/simulators/cpu_I6400/bin/qemu-mips64el -R 2147483648 -cpu I6400 -g 1234'
```

GDB is started on follwing way:

```
GDB=<PROJECT>/toolchains/mips-img-linux-gnu/2015.01-7/bin/mips-img-linux-gnu-gdb
${GDB} <PROJECT>/v8/out/mips64el.debug/cctest
(gdb) target remote localhost:1234
```

The problem starts in function `_dl_start`:

```
(gdb) disassemble $pc
Dump of assembler code for function _dl_start:
   0x000000007f7cee68 <+0>: daddiu  sp,sp,-1680
   0x000000007f7cee6c <+4>: sd  gp,1656(sp)
   0x000000007f7cee70 <+8>: lui gp,0x3
   ...
   ...
   0x000000007f7cf088 <+544>:   dsubu   a1,a2,v0
=> 0x000000007f7cf08c <+548>:   bltuc   a6,a1,0x7f7cf0a0 <_dl_start+568>
   0x000000007f7cf090 <+552>:   dsubu   v0,t0,v0
   0x000000007f7cf094 <+556>:   dlsa    v0,v0,sp,0x3
   ...
   ...
   0x000000007f7cf74c <+2276>:  b   0x7f7cf6ec <_dl_start+2180>
   0x000000007f7cf750 <+2280>:  daddiu  a0,a0,-1760
End of assembler dump.

(gdb) x /vi $pc
=> 0x7f7cf08c <_dl_start+548>:  bltuc   a6,a1,0x7f7cf0a0 <_dl_start+568>

(gdb) si
warning: GDB can't find the start of the function at 0x7f3971bc.

Program received signal SIGABRT, Aborted.
0x000000007f3971bc in ?? ()
(gdb) 
```

The problem starts after instruction `BLTUC`.  Also, in generated assembler code was possible to find microMIPS instructions (for example: `JRC` from release 5).

**Comment by ilijapavlovic** [comment] 2016-06-15 09:28
```
(gdb) x /vi $pc
=> 0x7f7cf08c <_dl_start+548>:  bltuc   a6,a1,0x7f7cf0a0 <_dl_start+568>

(gdb) info registers a6 a1
a6: 0xf
a1: 0x3


BLTUC: 
cond <- unsigned(GPR[rs]) < unsigned(GPR[rt])
cond <- (a6 < a1)
cond <- (0xf < 0x3)
```

According this, branching should not be performed, and execution should be continued on instruction located in at `0x000000007f7cf090`

**Comment by ilijapavlovic** [comment] 2016-06-16 12:40
Encoding instruction `BLTUC` is checked and it seems OK.

```
(gdb) x /xw 0x7f7cf08c
0x7f7cf08c <_dl_start+548>: 0x1d450004

(gdb) x /i 0x7f7cf08c
   0x7f7cf08c <_dl_start+548>:  bltuc   a6,a1,0x7f7cf0a0 <_dl_start+568>
```

0x1d450004    = 000111 01010 00101 0000000000000100

offset = 4
target_offset = offset << 2 = 16
PC = PC + 4 + target_offset = PC + 20 = (_dl_start+548) + 20 = _dl_start+568

**Comment by ilijapavlovic** [comment] 2016-06-23 08:01
The small code snippet is made and it contains `JRC` instruction (alias for `JIC rt, 0`) which belongs Release 6 Instruction Set:

```
//
// <PROJECT>/examples/test_inline_asm.cc
//
#include <cstdint>

int main(int argc, char * argv[]) {
  int32_t *target_address = reinterpret_cast<int32_t*>(main) + 11;

  __asm__ (
    // AssemblerTemplate
    "li $a0, 4321\n\t"
    "daddiu $a0, $a0, 1\n\t"
    "jrc %[addr]\n\t"         // jump to daddiu $a0,$a0,5
    "daddiu $a0, $a0, 2\n\t"
    "daddiu $a0, $a0, 3\n\t"
    "daddiu $a0, $a0, 4\n\t"
    "daddiu $a0, $a0, 5\n\t"  // <-----
    "daddiu $a0, $a0, 6\n\t"
    "daddiu $a0, $a0, 7\n\t"
    "daddiu $a0, $a0, 8\n\t"
    "daddiu $a0, $a0, 9\n\t"
    "daddiu $a0, $a0, 10\n\t"
    : /* OutputOperands */
    : /* InputOperands  */  [addr] "r" (target_address)
  );

  return 0;
}
```

The first commit, where this example was possible to compile without errors, is:

```
commit af1866f46288166e6c7b1a3ac07ed19a392aeea1
Author: v8-autoroll <v8-autoroll@chromium.org>
Date:   Thu Apr 21 02:11:36 2016 -0700

    Update V8 DEPS.
```

The example is compiled with following command:

```
$ <PROJECT>/v8/third_party/llvm-build/Release+Asserts/bin/clang++ --target=mips64el-img-linux-gnu -stdlib=libstdc++ --gcc-toolchain=<PROJECT>/toolchains/mips-img-linux-gnu/2015.01-7 -integrated-as -EL -mhard-float -mips64r6 -mabi=64 -static -O3 -std=gnu++11 -MMD <PROJECT>/examples/test_inline_asm.cc -o <PROJECT>/examples/test_inline_asm
```

This kind of execution on Qemu produces an error:

```
$ cd <PROJECT>/examples
$ <PROJECT>/simulators/cpu/bin/qemu-mips64el -R 2147483648 -cpu MIPS64R6-generic -d in_asm -D test_inline_asm.qemu.log test_inline_asm
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```

Execution this example without option `-R 2147483648` will cause successful execution of the program:

```
$ cd <PROJECT>/examples
$ <PROJECT>/simulators/cpu/bin/qemu-mips64el -cpu MIPS64R6-generic -d in_asm -D test_inline_asm.qemu.log test_inline_asm
```

Part of Qemu execution log which shows that `JIC` instruction is executed:

```
...
IN: main
0x0000000120004400:  lui        at,0xb
0x0000000120004404:  daddu      at,at,t9
0x0000000120004408:  daddiu     at,at,14512
0x000000012000440c:  ld at,-32736(at)
0x0000000120004410:  daddiu     v0,at,44
0x0000000120004414:  li a0,4321
0x0000000120004418:  daddiu     a0,a0,1
0x000000012000441c:  jic        v0,0

IN: main
0x000000012000442c:  daddiu     a0,a0,5
0x0000000120004430:  daddiu     a0,a0,6
0x0000000120004434:  daddiu     a0,a0,7
0x0000000120004438:  daddiu     a0,a0,8
0x000000012000443c:  daddiu     a0,a0,9
0x0000000120004440:  daddiu     a0,a0,10
0x0000000120004444:  jr ra
0x0000000120004448:  li v0,0
...
```

**Comment by ibogosavljevic** [comment] 2016-06-24 13:51
The problem appeared in commit 

```
d22a7ed415e82d9d349e9191075a1a00cd8806ba

Update V8 DEPS.

Rolling v8/tools/clang to 51bba1037858028f42141689ed1b3b63a20f0b52

TBR=machenbach@chromium.org,vogelheim@chromium.org,hablich@chromium.org

Review URL: https://codereview.chromium.org/1838013003

Cr-Commit-Position: refs/heads/master@{#35088} 
```

With this version of CLANG, all tests are failing with weird error messages. This commit corresponds to the trunk version of clang 263324. This version of CLANG introduced branch-compact instructions instead of branch instructions with delay slot (the most obvious thing in assembler code produced by the compiler). 

Testing with the newest version of CLANG trunk 270823 shows that the problem is fixed and we don't see the failures. Testing has been done in debug mode because CLANG crashes when compiling in release mode.

Related to CLANG trunk 270823 crashing when compiling MIPS64R6 in release mode: according to the CLANG team, the issue existed in trunk 269902 and was fixed in 272259. It is fixed here: https://dmz-portal.mips.com/bugz/show_bug.cgi?id=2342.

**Closed as completed by ibogosavljevic** 2016-06-24 13:51 UTC
