### ISSUE TITLE
Bughunting: RunWord32AndAndWord32ShrP, RunWord32OrP, RunWord32ShrP, RunWord32XorP

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#310] opened 2016-05-06 11:04 UTC
These tests are failing: 
RunWord32AndAndWord32ShrP, RunWord32OrP, RunWord32ShrP, RunWord32XorP

Since the following builds:

Target - MIPS64 - edge: https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge/builds/4903
Target - MIPS64 - edge - mipsr6,under qemu: https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20edge%20-%20mipsr6,under%20qemu/builds/2800
Target - MIPS64 - Debug - edge - mipsr6,under qemu,quick: https://v8.mips.com/bbv8/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20mipsr6,under%20qemu,quick/builds/2330
Target - MIPS64 - Debug - edge - clang: https://v8.mips.com/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20clang/builds/331
Target - MIPS64 - Debug - edge: https://v8.mips.com/builders/Target%20-%20MIPS64%20-%20Debug%20-%20edge/builds/1138
Target - MIPS64 - edge - clang: https://v8.mips.com/builders/Target%20-%20MIPS64%20-%20edge%20-%20clang/builds/1140

**Comment by kilvadyb** [comment] 2016-05-09 14:47
Not related to fix CL of #302, bug disappeared after landing CL of #311.

**Comment by kilvadyb** [comment] 2016-05-09 15:35
Failure still exists on our buildbots while I cannot reproduce them on our er8 board.

**Comment by palfia** [comment] 2016-05-30 11:10
Fails since the lwu TF operator is added in: https://codereview.chromium.org/1907363002

**Comment by marijantic** [comment] 2016-05-31 08:55
Error message under qemu:

Fatal error in ../test/cctest/compiler/test-run-machops.cc, line 2664
Check failed: expected == bt.call(*i, *j) (4294967295 vs. 4294967295).

**Comment by marijantic** [comment] 2016-06-15 14:31
Our issue seems to be related to: 
https://bugs.chromium.org/p/v8/issues/detail?id=4037

**Comment by marijantic** [comment] 2016-06-16 13:38
Forcing the test to use CheckEQImpl<uint32_t, uint32_t> instead of using CHECK_EQ macro fixes the test failure. This is not the actual solution, but shows that the problem is in check macro.

**Comment by marijantic** [comment] 2016-07-12 10:36
In debug mode, sw/lw is used to store and load relevant part of the result into memory. In this case, comparison passes.
In release mode,  values in 64-bit registers are compared, no matter the value is cast to uint32_t. 
I added the sign extension as Balazs's suggested https://github.com/v8mips/v8mips/wiki/Unsigned-32-bit-values-in-Turbofan-on-mips64: "all the uint32_t input values must be sign-extended to int64_t before executing an operation which don't have 32-bit version ".

**Comment by marijantic** [comment] 2016-07-13 07:44
PTAL: https://codereview.chromium.org/2147883002/

Fix landed as edf8c03547bb46247cbcdda2152a5e6e105b8ae8

**Comment by marijantic** [comment] 2016-07-14 10:32
RunWord32AndAndWord32ShrP and RunWord32ShrP are still failing on the build bots, but the issue does not reproduce on the Broadcom XLP board used for testing locally. 
The committed fix did not introduce changes to shift operators, I will add these changes also.

**Comment by marijantic** [comment] 2016-07-22 06:42
Fix for shr/sra landed as https://chromium.googlesource.com/v8/v8/+/24d432cb8253eac55cb3649144809af3d43e634b

**Closed as completed** 2016-07-22 06:42 UTC
Labels: pri1
