### ISSUE TITLE
CLANG compilation issue on build bot

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#326] opened 2016-06-01 12:56 UTC
The v8 doesn't compile using CLANG anymore: 
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang%20-%20builder/builds/2571/steps/compile/logs/stdio

Please see what is the problem.

**Comment by ilijapavlovic** [comment] 2016-06-01 13:21
The problem is reproduced.

**Comment by ilijapavlovic** [comment] 2016-06-01 13:29
The problem appears from following build:
https://v8.mips.com/bbv8/builders/Target%20-%20edge%20-%20clang%20-%20builder/builds/2548

Problematical commit:

```
commit c88d7579b529d555472ad539fcbbf6057079d316
Author: v8-autoroll <v8-autoroll@chromium.org>
Date:   Sat May 28 14:56:58 2016 -0700

    Update V8 DEPS.

    Rolling v8/build to 10d3723f73a8bfb0bcbee33f368d92dea8ad1bd7

    Rolling v8/tools/clang to ef8e028ea0f0fdf3be7be6e817e5c26c8ba7aebe

    TBR=machenbach@chromium.org,vogelheim@chromium.org,hablich@chromium.org

    Review-Url: https://codereview.chromium.org/2021623002
    Cr-Commit-Position: refs/heads/master@{#36566}

```

**Comment by ilijapavlovic** [comment] 2016-06-03 08:21
Problematical commit contains these changes:

```
diff --git a/DEPS b/DEPS
index a7afa89..6a8e87f 100644
--- a/DEPS
+++ b/DEPS
@@ -8,7 +8,7 @@ vars = {

 deps = {
   "v8/build":
-    Var("git_url") + "/chromium/src/build.git" + "@" + "d96032ba08a39623c95c377a5f592f9931c93385",
+    Var("git_url") + "/chromium/src/build.git" + "@" + "10d3723f73a8bfb0bcbee33f368d92dea8ad1bd7",
   "v8/tools/gyp":
     Var("git_url") + "/external/gyp.git" + "@" + "bce1c7793010574d88d7915e2d55395213ac63d1",
   "v8/third_party/icu":
@@ -31,7 +31,7 @@ deps = {
   "v8/test/test262/data":
     Var("git_url") + "/external/github.com/tc39/test262.git" + "@" + "9c45e2ac684bae64614d8eb55789cae97323a7e7",
   "v8/tools/clang":
-    Var("git_url") + "/chromium/src/tools/clang.git" + "@" + "5c08263d87fd4fe23df4f73323cd6146f5dfe7b2",
+    Var("git_url") + "/chromium/src/tools/clang.git" + "@" + "ef8e028ea0f0fdf3be7be6e817e5c26c8ba7aebe",
 }

 deps_os = {
```

The commit used as starting point for testing is following:

```
commit aff90bc15b548fa5e6202e82031413bea1e7fc6b
Author: rmcilroy <rmcilroy@chromium.org>
Date:   Fri May 27 15:29:01 2016 -0700

    [Interpreter] Add intrinsic for Runtime::kInlineCall.

    One of the top runtime calls in many workloads is Runtime_Call. Add an
    intrinsic for the interpreter to inline this runtime call.

    BUG=v8:4280
    LOG=N

    Review-Url: https://codereview.chromium.org/2019433003
    Cr-Commit-Position: refs/heads/master@{#36565}
```

Here are results of testing:

```
$ egrep '/chromium/src/build.git|/chromium/src/tools/clang.git' DEPS
    Var("git_url") + "/chromium/src/build.git" + "@" + "d96032ba08a39623c95c377a5f592f9931c93385",
    Var("git_url") + "/chromium/src/tools/clang.git" + "@" + "5c08263d87fd4fe23df4f73323cd6146f5dfe7b2",
```
- V8 build successful.

```
$ egrep '/chromium/src/build.git|/chromium/src/tools/clang.git' DEPS
    Var("git_url") + "/chromium/src/build.git" + "@" + "10d3723f73a8bfb0bcbee33f368d92dea8ad1bd7",    // <--- new commit
    Var("git_url") + "/chromium/src/tools/clang.git" + "@" + "5c08263d87fd4fe23df4f73323cd6146f5dfe7b2",
```
- V8 build successful.

```
$ egrep '/chromium/src/build.git|/chromium/src/tools/clang.git' DEPS
    Var("git_url") + "/chromium/src/build.git" + "@" + "d96032ba08a39623c95c377a5f592f9931c93385",
    Var("git_url") + "/chromium/src/tools/clang.git" + "@" + "ef8e028ea0f0fdf3be7be6e817e5c26c8ba7aebe",   // <--- new commit
```
- V8 build fails.

The cause of the problem is in committed Clang tool.

**Comment by ilijapavlovic** [comment] 2016-06-03 08:28
With mentioned Clang commit, the only change is in `tools/clang/scripts/update.py` where `CLANG_REVISION` parameter is changed from `CLANG_REVISION = '269902'` into `CLANG_REVISION = '270823'`.

**Comment by ilijapavlovic** [comment] 2016-06-03 08:30
```
commit ef8e028ea0f0fdf3be7be6e817e5c26c8ba7aebe
Author: krasin <krasin@google.com>
Date:   Thu May 26 21:39:09 2016 -0700

    Roll clang 269902:270823.

    Ran `./tools/clang/scripts/upload_revision.py 270823`.

    BUG=614933

    Review-Url: https://codereview.chromium.org/2015793003
    Cr-Original-Commit-Position: refs/heads/master@{#396388}
    Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
    Cr-Mirrored-Commit: 709225ae8e282d53833e01e52d552d1178917951
```

**Comment by ilijapavlovic** [comment] 2016-06-03 11:51
Solution for this problem is to set environment variable CLANG_ARGS on correct value.
Environment variable CLANG_ARGS contains option `--target=${ARCH}-linux-gnu` which 
should adapted into  `--target=${ARCH}-mti-linux-gnu` for release R2.

```
mips.r2)
  ARCH=mips-mti

mipsel.r2)
  ARCH=mipsel-mti

mips64.r2)
  ARCH=mips64-mti

mips64el.r2)
  ARCH=mips64el-mti


CLANG_BASE=${PROJECT}/v8/third_party/llvm-build
CLANG_BINDIR=${CLANG_BASE}/Release+Asserts/bin
CLANG_ARGS="--target=${ARCH}-linux-gnu -stdlib=libstdc++ --gcc-toolchain=${TC_BASE}"

CLANG=${CLANG_BINDIR}/clang
CLANGXX=${CLANG_BINDIR}/clang++

export CC="${CLANG} ${CLANG_ARGS}"
export CXX="${CLANGXX} ${CLANG_ARGS}"
export CPP="${CLANG} ${CLANG_ARGS} -E"
export LINK="${CLANGXX} ${CLANG_ARGS}"
export CC_host="${CLANG}"
export CXX_host="${CLANGXX}"
export CPP_host="${CLANG} -E"
export LINK_host="${CLANGXX}"
```

With these adaptations, V8 build is successfully finished.
Tested targets for R2 release: mips, mipsel, mips64, mips64el.

**Closed as completed** 2016-06-03 11:51 UTC
