### ISSUE TITLE
Bughunting: mjsunit/wasm/params

### ISSUE THREAD

**Issue by kilvadyb** [v8mips/v8mips#269] opened 2016-03-07 18:21 UTC

**Comment by marijantic** [comment] 2016-03-09 13:01
https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/6639/steps/Check/logs/params

**Comment by marijantic** [comment] 2016-03-09 13:04
The first build to experience the issue: https://v8.mips.com/bbv8/builders/Target%20-%20edge/builds/6506

**Comment by marijantic** [comment] 2016-03-09 16:23
The issue does not repro on the ci20 board. Tests are running on the Popcorn board, so this seems to be the hardware issue.

**Comment by ibogosavljevic** [comment] 2017-01-17 09:25
This issue does not reproduce for a very long time, so closing it.

**Closed as completed by ibogosavljevic** 2017-01-17 09:25 UTC
Labels: on-hold, build-failure
