### ISSUE TITLE
Add i18n support for big endian to upstream.

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#197] opened 2015-10-16 01:28 UTC
We get i18n support from third_party/icu, which is from https://chromium.googlesource.com/chromium/deps/icu.git (I don't know if that is the real upstream, or if that is a chromium-specific mirror or an independent project.)

I was told that we can get the source, and rebuild icu to include support for MIPS big-endian. 

We should do that manually to test. If it works, then we should try to upstream that support, so that it comes in the Chromium version.

We would like to have full icu support for both mips32 and 64 big-endian, for our own testing, and to be used in node.js.

Please do check if this support would have side-effects to other architectures, for instance, would it increase the size of binaries, or anything like that. We would like to anticipate any objections the upstream maintainers might have.

**Comment by paul99** [comment] 2015-10-19 02:36
on 2015-10-16, @mkaric wrote in slack:

> I just tried compiling mips and mips64 BE following instructions on github wiki - Building v8 for BE with QEMU. I compiled without i18nsupport=off flag, it worked in release and debug mode and return-normalized-string test passes in all cases. With i18nsupport=off flag it fails in all cases.

This is good news, and we can start using i18n for big-endian then.

But I would like to track down the details, and understand precisely how/why this works.

There are ICU data tables build by Chromium team, per README.chromium in the repo. Back when ICU4.6 was current, there was _not_ big-endian support. (I will forward some related emails.)

I'd like to see what changes enabled it. It might be in the Chromium-specific build scripts, but it might also need changes in the upstream ICU project files as well. 

Can you investigate and document here  the changes that made this work? 

As a second step, can you please run the `check` tests without the `--no-i18n` flag so that we can see if _all_ the tests now pass on mips and mips64 'eb'?

(I'm putting this as P1, since if it does work, let's just get this documented quickly and get the bots using it)

**Comment by paul99** [comment] 2015-10-20 00:52
@mkaric So it does not look to me like this works at all. 

If I build _without_ the option `i18nsupport=off`, (in other words, i18n support is on) the build completes, and it runs the tests, but with lots of failures.

```
tools/run-tests.py -j2 --arch=mips64 --mode=release  --timeout=240 --verbose --time --no-presubmit --report test262/built-ins/String/prototype/normalize/return-normalized-string*
[00:02|% 100|+  16|-   8]: Done     (results file posted on slack)
```

Similar for testing 'intl' tests:

```
tools/run-tests.py -j4 --arch=mips64 --mode=optdebug --timeout=120 --verbose --time --no-presubmit --report intl
[01:16|% 100|+  36|- 164]: Done     (details on slack #bigendian)
```

Very oddly a few _more_ tests pass when compiled with i18support=off :

```
[00:54|% 100|+  40|- 160]: Done
```

(Similar results for mips32 big-endian)

**Comment by paul99** [comment] 2015-11-06 07:21
@mkaric please update the issue with any new status, but IIUC, a manually built ICU data file for big-endian (built on mips EB board) can be used for EB builds, and _all_ intl tests pass. Please correct any mis-statements here.

I understand that fixing the ICU code to allow building EB data file in EL host machine will be challenging. So let's postpone that for a while.

Let's start now by adding a new wiki page that describes how to build the EB data file, and where to place it in build tree, and include a patch for tie icu.gyp file to allow proper builds for MIPS EB on _both_ MIPS EB Linux build host, building v8 natively, and on x86 host cross-compiling. It should work with or without qemu-based snapshot building on the x86 host.

I will ask the IBM folks to try this on their PPC EB builds. If you know the right gyp-file settings to allow PPC big-endian to work, add them. If not we can get a patch from them.

Second step is we should add pre-built binary on the wiki page for convenience, but we would want to prevent that from getting stale, by tracking ICU DEPS rolls in v8, and (auto) updating the file. If this can all be scripted, that would be ideal.

Third step is we can look at creating this file with Qemu. Brendan pointed out that we should be to cross-compile the code that generates the file using a MIPS compiler on x86. Then we should just need user-mode Qemu to run that executable to actually produce the binary. This would be far superior to requiring system-mode Qemu.

**Comment by mkaric** [comment] 2015-11-09 17:07
ICU data file for big-endian can be built on mips EB board and system mode qemu. With this file all intl tests pass, as well as previously failing test262 tests.

I also tried using icupkg tool from ICU and a script I wrote to generate big-endian data file, but the generated file is not identical to the one obtained when building on the EB board and the tests fail.

**Comment by mkaric** [comment] 2015-11-12 11:56
Here is an overview of what has been done and tried on this issue:

ICU chromium source tree contains only little-endian ICU data files (source/data/in/icudtl.dat and linux/icutdl_dat.S). Generating big-endian data is possible by building ICU on a BE board or system mode qemu (described in wiki, https://github.com/paul99/v8m-rb/wiki/Building-v8-for-BE-with-internationalization-support). When the files are built and placed at the correct location, it is necessary to make changes to icu.gyp file so the compiler finds BE data files when building v8 (also explained in wiki). 

I tried cross-compiling ICU on a LE machine for a BE target but generated data files are incorrect (steps for doing this below). There is a bug report (http://bugs.icu-project.org/trac/ticket/7546) which states cross-compilaton where build host and target have different endianness result in incorrect library/data files. 

Another thing I tried is the icupkg tool which is generated when building icu. This tool is supposed to be able to change endianness of icupkg.dat but the resulting file is slightly different from the one generated on BE board and the internationalization tests fail. 

I tried building the icu from the original icu repository (http://source.icu-project.org/repos/icu/icu/tags/release-54-1) and placing these (unpatched) data files in v8 and the tests pass.

**Comment by mkaric** [comment] 2015-11-12 12:18
These are steps for cross-compiling ICU on a LE machine for a BE target but this will generate incorrect data files!

```
Generating ICU big endian data files on x64 machine running linux:

a. First we build for host, make sure environment variables for cross compile

toolchain are not set. Run

export CHROME_ICU_TREE_TOP=(path to v8)/third_party/icu 

b. Make a icu data build directory outside the Chromium source tree

   and cd to that directory, $ICUBUILDIR.

c. Run

${CHROME_ICU_TREE_TOP}/source/runConfigureICU Linux --build=x86_64-linux-gnu --host=x86_64-linux-gnu --disable-layout

d. Run 'make'

e. 'make' will fail when pkgdata looks for css3transform.res.

   See http://bugs.icu-project.org/trac/ticket/10570

f. Run

cd data

make

sed -i 's/css3transform.res/root.res/' out/tmp/icudata.lst

make

cp out/tmp/icudt[5-9][0-9]l.dat "${CHROME_ICU_TREE_TOP}/source/data/in/icudtl.dat"

cp out/tmp/icudt[5-9][0-9]l_dat.S "${CHROME_ICU_TREE_TOP}/linux/icudtl_dat.S"

g. Now we cross compile for mips target, make a icu data cross build directory 

   outside the Chromium source tree and cd to that directory, $ICUCROSSBUILDIR.

h. Set toolchain environment variables for mips BE target, I used 2015.1-7 MTI toolchain set for mips32r2 BE target. Run

${CHROME_ICU_TREE_TOP}/source/runConfigureICU Linux --host=x86_64-linux-gnu --build=mips-linux-gnu --disable-layout --with-cross-build=$ICUBUILDIR

i. Run 'make'

j. Again 'make' will fail when pkgdata looks for css3transform.res.

k. Run

cd data

make

sed -i 's/css3transform.res/root.res/' out/tmp/icudata.lst

make

cp out/tmp/icudt[5-9][0-9]b.dat "${CHROME_ICU_TREE_TOP}/source/data/in/icudtb.dat"

cp out/tmp/icudt[5-9][0-9]b_dat.S "${CHROME_ICU_TREE_TOP}/linux/icudtb_dat.S"
```

**Comment by kisg** [comment] 2016-02-15 08:17
@mkaric: I have a couple questions:
- Do I understand correctly, that in the ICU tree there is no place for storing prebuilt big endian binaries, because the build system looks for them under the same name as the LE versions?
- How is BE chromium and V8 built by Google? Are they rebuilding ICU for BE, so this is not an issue for them?
- Do you have a suggestion to make sure that we can build v8 in BE mode with i18n enabled (e.g. on our bots)?

**Comment by mkaric** [comment] 2016-02-15 10:39
Naming is not the problem, BE binaries have a 'b' in the name, while LE have an 'l'. The problem is that it is not simple to generate BE binaries, and BE accounts for a small fraction of chromium users so there is not enough incentive for the effort to generate these binaries. If we can make it simple enough then maybe it would be possible to get BE binaries included with chromium ICU.

Currently it is only possible to generate BE binaries on a BE board. There is a bug in ICU that causes binaries generated by cross-compilation to be invalid. Currently whenever there is a new version of ICU I generate new binaries on the board and copy them to our wiki page: https://github.com/v8mips/v8mips/wiki/Building-v8-for-BE-with-internationalization-support. 

I am not sure what Google does, but I believe they build V8 without internationalization support.

The best solution of course would be to get BE binaries included in chromium ICU. Hopefully if we could get cross-compilation to work, chromium ICU team would be willing to generate BE binaries and include them. Current solution is building BE binaries by hand on a BE board and putting it on the wiki so whoever needs them can get them there. We agreed for now to leave this on hold for now, but when I have the time I will look into fixing ICU cross-compilation.

**Comment by mkaric** [comment] 2016-02-24 10:08
There is a way to generate BE binaries on a LE machine. First we build ICU on a LE machine and generate LE ICU binaries. Then we use the icupkg tool generated during the ICU build, to convert LE data file to BE data file. Then using a provided python script we convert the BE data file into a form required for v8 compilation. When using the icupkg tool, the length of the input and output file names must be equal, otherwise the generated file will be incorrect. 

Here are the steps to generate BE binaries on a LE machine:

```
Generating ICU big endian data files on x64 machine running linux:
a. First we build for host, make sure environment variables for cross compile
toolchain are not set. Run

export CHROME_ICU_TREE_TOP=(path to v8)/third_party/icu 

b. Make a icu data build directory outside the Chromium source tree
   and cd to that directory, $ICUBUILDIR.

c. Run

${CHROME_ICU_TREE_TOP}/source/runConfigureICU Linux --disable-layout

d. Run 'make'
e. 'make' will fail when pkgdata looks for css3transform.res.
   See http://bugs.icu-project.org/trac/ticket/10570
f. Run

cd data
make
sed -i 's/css3transform.res/root.res/' out/tmp/icudata.lst
make
cp out/tmp/icudt[5-9][0-9]l.dat "${CHROME_ICU_TREE_TOP}/source/data/in/icudtl.dat"
cp out/tmp/icudt[5-9][0-9]l_dat.S "${CHROME_ICU_TREE_TOP}/linux/icudtl_dat.S"

g. Use icupkg tool to generate BE .dat file from LE .dat file. Run

for file in out/tmp/icudt[5-9][0-9]l.dat; do ../bin/icupkg -tb "$file" "${file/l/b}"; done

h. Use the provided script, gen_datS.py, to generate BE .S file from BE .dat file. Copy
the script to the build directory, $ICUBUILDIR, and then run

for file in out/tmp/icudt[5-9][0-9]b.dat; do ../gen_datS.py "$file" "${file/.dat/_dat.S}"; done

i. Copy BE data files to the appropriate location

cp out/tmp/icudt[5-9][0-9]b.dat "${CHROME_ICU_TREE_TOP}/source/data/in/icudtb.dat"
cp out/tmp/icudt[5-9][0-9]b_dat.S "${CHROME_ICU_TREE_TOP}/linux/icudtb_dat.S"
```

The script, gen_datS.py, is given here:

```
#!/usr/bin/env python

import binascii
import sys

if len(sys.argv)<3:
    print "Provide input and output file names as arguments to use the script!"
else:
    input_file = sys.argv[1];
    output_file = sys.argv[2];

    input = open(input_file, 'rb').read()

    output = open(output_file, 'w')

    output.write(".globl icudt54_dat\n")
    output.write("\t.section .note.GNU-stack,\"\",%progbits\n")
    output.write("\t.section .rodata\n")
    output.write("\t.balign 16\n")
    output.write("#ifdef U_HIDE_DATA_SYMBOL\n")
    output.write("\t.hidden icudt54_dat\n")
    output.write("#endif\n")
    output.write("\t.type icudt54_dat,%object\n")
    output.write("icudt54_dat:\n")

    split = [binascii.hexlify(input[i:i+4]).upper().lstrip('0') for i in range(0, len(input), 4)]

    for i in range(len(split)):
        if (len(split[i])==0):
            split[i]='0'
        elif (len(split[i])==1):
            if not any((c in '123456789') for c in split[i]):
                split[i]='0x0'+split[i]
        elif (len(split[i])%2==1):
            split[i]='0x0'+split[i]
        else:
            split[i]='0x'+split[i]

    for i in range(len(split)):
        if (i%32==0):
            output.write("\n.long ")
        else:
            output.write(",")
        output.write(split[i])

    output.write("\n")
    output.close()
```

BE binaries generated this way, however, are not identical to those generated on a BE board. Still all intl tests pass, and differences are very small, so the binaries seem to be generated correctly.

**Comment by kisg** [comment] 2016-03-02 17:48
@mkaric: Please file a bug with Google about this. Include the link to this issue and also to our wiki page. Enter the link to the Google issue below.

**Comment by paul99** [comment] 2016-03-03 05:31
@kisg @mkaric - drive by comment: I suggest that you bring this to attention of the IBM team ( @mtbrandy ), ask them to test, and get their additions into the icu.gyp fix. Once we have a unified version for EB, then maybe ask Michael H. for help in getting the Chromium team to accept it. As Miran will remember, the Chromium guys were pretty hostile to previous work on this, and that is understandable, since no one wants a big-endian Chromium, and that is all they are thinking about. So the ask is all about improving v8 in the node.js ecosystem. This is definitely 2nd order priority for Google team, but Michael might be able to influence the right decision makers on behalf of MIPS & PPC.

**Comment by srl295** [comment] 2016-03-07 18:00
Hello. I chatted with @mhdawson about this. I work on ICU and on the integration into Node. There are a few options here.
- Get Chrome to add mips (or PPC, etc) data files

Chrome does its own fragile gyrations to build its ICU data. That's the tactic they've chosen, and the `third_party/icu` does not have all of ICU, but just the subset Chrome chose to package. Checking in the source raw assembly files wouldn't be my recommendation. @mkaric it's an impressive amount of work to try to make that build happen, above. I probably wouldn't recommend this path long ter.
- Build against a "system ICU"- discovered via `pkg-config` or by setting build flags.  

Do you already have ICU installed on the machine in question? You could dynamically link against it.  The `.gyp` for this is pretty simple, here's what I use in Node: https://github.com/nodejs/node/blob/master/tools/icu/icu-system.gyp 

If you add `CFLAGS` and `LDFLAGS` to match basically the output of `pkg-config icu-i18n --cflags --libs` this mechanism will work.
- Build against an arbitrarily downloaded ICU via `.gyp`

This is what Node does.  `.gyp` file is here: https://github.com/nodejs/node/blob/master/tools/icu/icu-generic.gyp  _but_ it takes some lifting by a python script to figure out which source files to include.

---

Those are some of the options.. In Node I'm also working on adding a subset of ICU directly into its repo - https://github.com/nodejs/node/issues/3476  

Please let me know how I can be of help.  We'd like to see this work for PPC-big endian also.

**Comment by mkaric** [comment] 2016-03-11 19:06
Bug filed, link to the issue:
https://bugs.chromium.org/p/v8/issues/detail?id=4828

**Comment by srl295** [comment] 2016-03-11 20:25
@mkaric OK, but as I noted above - that's a fix for _how Chromium builds ICU_. There are other ways.

**Comment by mkaric** [comment] 2016-07-22 12:13
The CL that enables i18n support for BE has landed:
https://codereview.chromium.org/2162393003

Now waiting for v8 deps update to enable intl tests for BE and other tests that require i18n support.

**Comment by mkaric** [comment] 2016-07-26 11:38
I tried setting icu to a new version and compiling v8 for mips64 big endian with i18n support, but the intl test suite still fails. The problem is the default icu data file which is set to "icudtl.dat" for all architectures. Setting this to "icudtb.dat" for big endian fixes this. Prepared a CL, PTAL:
https://codereview.chromium.org/2182043002/

**Comment by mkaric** [comment] 2016-08-16 08:51
New changes in Chromium ICU that enable i18n support for big endian have been rolled into v8. I will leave this open until we have BE buildbots running with i18n support.

**Comment by mkaric** [comment] 2016-08-17 09:07
Big endian buildbots running with i18n support, closing.

**Closed as completed by mkaric** 2016-08-17 09:07 UTC

**Comment by mkaric** [comment] 2016-08-24 10:27
@srl295 Hello, MIPS BE can now be built with i18n support, big endian data has been added to Chromium ICU. I understand this was not your preferred solution, but this way both LE and BE work in the same way. Adding PPC too should be a matter of just adding few conditions to icu.gyp file.
