### ISSUE TITLE
Bughunting: mjsunit/allocation-site-info

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#312] opened 2016-05-06 12:35 UTC
This is a flaky failure, appears in the MIPS64 bots sometimes.

Examples:
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/7430
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/7435

**Comment by ilijapavlovic** [comment] 2016-05-10 09:31
The problem is reproduced.

The command line for starting the test looks as follow:

```
${PROJECT}/v8/out/mips64el.debug/d8 --test --random-seed=${RANDOM_SEED} \
--nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts \
--debug-code --verify-heap --allow-natives-syntax --expose-gc --noalways-opt \
${PROJECT}/v8/test/mjsunit/mjsunit.js ${PROJECT}/v8/test/mjsunit/allocation-site-info.js

```

The test result depends on value of `${RANDOM_SEED}` parameter. Here are some of values from interval [-50, 50] where the test fails:

```
-50, 
-33, -31, -30,
-29, -27, -25, -23, -21,
-19, -16, -11, -10,
-5,
5,
10, 13, 14, 17,
22, 24, 29, 
30, 31, 32
```

The test always fails for listed values from the interval.

**Comment by kilvadyb** [comment] 2016-05-11 09:58
I reduced the test script to make a few generated code call (still good on arm64, fails on mips64el):

```
// Flags: --allow-natives-syntax --expose-gc
// Flags: --noalways-opt

var elements_kind = {
  fast_smi_only            :  'fast smi only elements',
  fast                     :  'fast elements',
  fast_double              :  'fast double elements',
  dictionary               :  'dictionary elements',
}

function getKind(obj) {
  if (%HasFastSmiElements(obj)) return elements_kind.fast_smi_only;
  if (%HasFastObjectElements(obj)) return elements_kind.fast;
  if (%HasFastDoubleElements(obj)) return elements_kind.fast_double;
  if (%HasDictionaryElements(obj)) return elements_kind.dictionary;
}

function assertKind(expected, obj, name_opt) {
  assertEquals(expected, getKind(obj), name_opt);
}

// Test gathering allocation site feedback for generic ics.
(function() {
  function make() { return new Array(); }
  function foo(a, i) { a[0] = i; }

  var a = make();
  assertKind(elements_kind.fast_smi_only, a);

  // Make the keyed store ic go generic.
  foo("howdy", 1);
  foo(a, 3.5);

  var b = make();
  assertKind(elements_kind.fast_double, b);
})();
```

I also added a printf() to see what is wrong and looks like the bug is in the new/copyShallow ArrayStub. The printf patch:

```
diff --git a/src/runtime/runtime-test.cc b/src/runtime/runtime-test.cc
index 61e9888..de03584 100644
--- a/src/runtime/runtime-test.cc
+++ b/src/runtime/runtime-test.cc
@@ -530,10 +530,21 @@ RUNTIME_FUNCTION(Runtime_InNewSpace) {
     return isolate->heap()->ToBoolean(obj->Has##Name()); \
   }

-ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(FastSmiElements)
+RUNTIME_FUNCTION(Runtime_HasFastSmiElements) {
+  CONVERT_ARG_CHECKED(JSObject, obj, 0);
+  PrintF("obj: %p, map: %p, offset: %d, heapOTag: %d, kMapOffset: %d\n", obj, obj->map(), Map::kBitField2Offset, kHeapObjectTag, HeapObject::kMapOffset);
+  return isolate->heap()->ToBoolean(obj->HasFastSmiElements());
+}
+
+RUNTIME_FUNCTION(Runtime_HasFastDoubleElements) {
+  CONVERT_ARG_CHECKED(JSObject, obj, 0);
+  return isolate->heap()->ToBoolean(obj->HasFastDoubleElements());
+}
+  
+//ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(FastSmiElements)
 ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(FastObjectElements)
 ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(FastSmiOrObjectElements)
-ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(FastDoubleElements)
+//ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(FastDoubleElements)
 ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(FastHoleyElements)
 ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(DictionaryElements)
 ELEMENTS_KIND_CHECK_RUNTIME_FUNCTION(SloppyArgumentsElements)
```

The printf shows that on arm64 the object has a different map pointer at the 2nd call while on mips64el it has the same map.

**Comment by ilijapavlovic** [comment] 2016-05-11 10:56
If the test is executed with following flags:

```
--trace --trace_track_allocation_sites --trace_creation_allocation_sites 
--trace_ic --trace_elements_transitions
```

in the trace successful test will have lines like these:

```
...
AllocationSite: JSArray 0x7fddb84ca381 site updated FAST_SMI_ELEMENTS->FAST_DOUBLE_ELEMENTS

elements transition [FAST_SMI_ELEMENTS -> FAST_DOUBLE_ELEMENTS] in ~foo+352 at ${PROJECT}/v8/test/mjsunit/allocation-site-info.js:481 for 0x50219bf1 <JS Array[0]> from 0x50219c21 <FixedArray[4]> to 0x50219c71 <FixedDoubleArray[4]>
...
```

**Comment by kilvadyb** [comment] 2016-05-11 17:48
It seems I was optimistic about this bug. When I comment out the `foo("howdy", 1);` line in the shortened test script then it passes.

**Comment by ilijapavlovic** [comment] 2016-05-16 12:55
If the test is executed with flags `--trace_sim --print_all_code`, following line can be found in the trace:

```
bne     a4, zero_reg, 21 -> 0x...
```

For successful case the branching is not performed, but in failed case it is done.

**Comment by ilijapavlovic** [comment] 2016-05-17 08:19
This is part of the trace for successful test execution:

```
...
  0x7ffa6d325d78   dfa50008       ld      a1, 8(sp)               0000000050219bf9  <-- [00007ffa6da22e20 ]    (452185 )
...
  0x58445800   24a8002f       addiu   a4, a1, 47              0000000050219c28
  0x58445804   01054026       xor     a4, a4, a1              00000000000007d1
  0x58445808   3c01fff0       lui     at, 0xfff0              fffffffffff00000
  0x5844580c   01014024       and     a4, a4, at              0000000000000000
  0x58445810   15000015       bne     a4, zero_reg, 21 -> 0x58445868
  0x58445818   1000000a       beq     zero_reg, zero_reg, 10 -> 0x58445844
...
```

Register `a1` contains a word value `0x50219bf9` so instruction `addiu a4, a1, 47` will be performed on expected way.

Here is a sample of the trace for unsuccessful test execution:

```
...
  0x7fd500c25d78   dfa50008       ld      a1, 8(sp)               00007fd500819bf9  <-- [00007fd500f6ee20 ]    (452185 )
...
  0x31245800   24a8002f       addiu   a4, a1, 47              0000000000819c28 
  0x31245804   01054026       xor     a4, a4, a1              00007fd5000007d1 
  0x31245808   3c01fff0       lui     at, 0xfff0              fffffffffff00000 
  0x3124580c   01014024       and     a4, a4, at              00007fd500000000 
  0x31245810   15000015       bne     a4, zero_reg, 21 -> 0x31245868    
```

In this case register `a1` has double word value `0x7fd500819bf9`. For instruction `addiu` in the specification is mentioned following: 

> Format: ADDIU rt, rs, immediate
> 
> Restrictions: If GPR rs does not contain a sign-extended 32-bit value (bits 63..31 equal), then the result of the operation is UNPREDICTABLE.

Therefore, instruction `addiu   a4, a1, 47` gives wrong value `0x819c28` instead `0x7fd500819c28`.
As more appropriate instruction here should be `daddiu`.

**Comment by ilijapavlovic** [comment] 2016-05-17 10:06
The simplest solution for this is implement ADDIU instruction for simulator on the same way as DADDIU.

**Comment by kilvadyb** [comment] 2016-05-17 15:59
Proposal CL: https://codereview.chromium.org/1989483002/

**Comment by kilvadyb** [comment] 2016-05-17 16:37
A DCHECK added to addiu simulation: https://codereview.chromium.org/1984313002/

**Comment by kilvadyb** [comment] 2016-05-18 10:54
Both CLs landed.

**Closed as completed by kilvadyb** 2016-05-18 10:54 UTC
