### ISSUE TITLE
Bughunting: cctest/test-heap-profiler/TrackBumpPointerAllocations

### ISSUE THREAD

**Issue by palfia** [v8mips/v8mips#260] opened 2016-02-29 11:53 UTC
New test failure in the buildbots: cctest/test-heap-profiler/TrackBumpPointerAllocations

https://build.chromium.org/p/client.v8/builders/V8%20Mips%20-%20big%20endian%20-%20nosnap%20-%201/builds/2895/steps/Check/logs/TrackBumpPointerAlloc..

**Comment by ibogosavljevic** [comment] 2016-03-01 09:00
The failure started to appear in commit  ba2077aac3a775523ca3fc9600fcf76f55e8d1c2

[stubs] Introduce a dedicated FastNewObjectStub.

Move the already existing fast case for %NewObject into a dedicated
FastNewObjectStub that we can utilize in places where we would otherwise
fallback to %NewObject immediately, which is rather expensive.

Also use FastNewObjectStub as the generic implementation of JSCreate,
which should make constructor inlining based on SharedFunctionInfo (w/o
specializing to a concrete closure) viable soon.

R=jarin@chromium.org

Review URL: https://codereview.chromium.org/1708313002

Cr-Commit-Position: refs/heads/master@{#34136}
Changed files

**Comment by ibogosavljevic** [comment] 2016-03-04 11:49
Fixed for MIPS32, patch landed and tests are passing:
https://chromium.googlesource.com/v8/v8/+/96efefd748aba2924a80aa1125cc973c03a53714

https://v8.mips.com/bbv8/builders/Sim%20-%20edge/builds/10374/steps/Check/logs/stdio

Tests are still failing on MIPS64, the same error is present as in MIPS32, but the problem isn't fixed with just that change

**Comment by ibogosavljevic** [comment] 2016-03-07 13:39
Fixed for MIPS64, test passing:
https://v8.mips.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge/builds/6992/steps/Check/logs/stdio

https://chromium.googlesource.com/v8/v8/+/cafe34ae4afbe3495983d615c4b8e1cd3721c4b5

**Closed as completed by ibogosavljevic** 2016-03-07 13:39 UTC
Labels: pri1
