### ISSUE TITLE
Use r6 AUI to improve load/stores that use LoadRegPlusOffsetToAt()

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#219] opened 2015-11-23 03:04 UTC
Currently if we do a `lw()` with larger than 16-bit offset, we call LoadRegPlusOffsetToAt() which has 3 instructions, then do the `lw()` from (at, 0) which is total of 4 instructions.

With AUI we can do this in 2 instructions:

```
AUI at, (rbase, imm >> 16)
LW rd, (at, imm & 0xffff)
```

Of course, we have to refactor both the load/stores themselves, and the LoadRegPlusOffsetToAt() function.

Note this works for all load/store, int/fp. We should do this, but priority is low, as we do not do large offsets frequently as far as I know (maybe that should be tested).

This can work for even large offsets on mips64 with DAHI, DATI, but there is no evidence that we use that. Due to memory management paging, I can't imagine we'd have legitimate offsets larger than the v8 page size of 1MB.

Please think about what other scenarios this instruction can be used.

Leaving unassigned for the moment.

**Comment by lialan** [comment] 2015-12-01 13:54
Just want to put a comment here: when doing the implementation pay attention to the fact that AUI adds an unsigned number, while LW is actually using a signed offset. So this becomes tricker.

Depending on the value of (imm & 0xffff), if it is a signed value then we need to do the following: (might not be accurate)

```
AUI at, (rbase, (imm >> 16 + 1))  <-- loading a higher value
LW rd, (at, imm - (imm >> 16 + 1))   <-- use negative offset here for loading
```

**Comment by lialan** [comment] 2015-12-04 01:09
I have submitted a CL for this, PTAL:

```
https://codereview.chromium.org/1493913006
```

**Comment by ibogosavljevic** [comment] 2017-02-17 14:25
Duplicate of #428 

Close.

**Closed as completed by ibogosavljevic** 2017-02-17 14:25 UTC
Labels: pri3, r6
