### ISSUE TITLE
MIPS on simulator is a lot slower than ARM

### ISSUE THREAD

**Issue by kalmard** [v8mips/v8mips#11] opened 2012-04-24 14:16 UTC
While this most likely only affects simulator testing, it raises two questions.
1. why? The difference is major. Is our simulator implementation slower, are we emitting more instructions, or is this an actual bug?
2. If it's a bug or MIPS-specific problem, what if it affects native code as well?

I ran some very simple tests:
tools/test.py --mode=release --simulator=arm cctest mjsunit -j8
and the same with mips.

The results:
ARM sim test: 11 min, 1 timeout. MIPS: 17 min, 2 timeouts

I know this is not a very scientific approach but there must be a reason why the exact same configuration runs 1.5 times slower on MIPS.

**Comment by paul99** [comment] 2012-04-25 00:54
1. I confirmed 50% slower performance on mips over arm in sim running tests (except for mozilla, which seems dominated by timeouts)
2. We should run mjsunit or cctest on representative mips & arm HW (8646 & beagle-board), maybe after using benchmark results to do a speed-factor correction. I suggest SunSpider for this, which is not nearly as optimizable as v8-bench, and may represent the performance of test-suite better.
3. Assuming that we prove it is the Sim, then we may want to do some comparative profiling of the simulator code itself.
4. A more-or-less unrelated fact, when running Android v8/webkit/browser under Qemu, it seems that mips is faster than Arm. Or at least the reported benchmark scores are about 50% better on mips. That could be due to the way time is counted inside the Qemu, I am not sure.

Can Daniel or Akos take a look at item 2, the hw speed compare, and report back?

**Comment by paul99** [comment] 2014-05-16 04:44
This old bug has never been addressed, our sim performance kind of sucks, and it needs to be fixed. I am sure this affects mips64 as much as mips32.

```
2014-04-30 08:10 
on trunk commit dc33fd73208  Version 3.26.28 (based on bleeding_edge revision r21063)
mipsel sim release quickcheck (not including build time)

[11:51|% 100|+ 8804|-   0]: Done                                               

real    12m5.058s
user    119m20.320s
sys  1m5.770s
```

here is the arm quickcheck

```
$ time make arm.release.quickcheck -j12 
>>> Running tests for arm.release
[05:25|% 100|+ 8791|-   0]: Done                                               

real    5m29.401s
user    53m47.360s
sys 0m57.840s
```

I suppose we should check arm64 as well, but our sim is very slow compared to arm, and it seems me that the mips instruction set should be simpler to simulate. So we probably just have some simple perf bottleneck that will show up on profiling.

**Comment by paul99** [comment] 2014-05-16 17:27
Here is an interesting in-progress CL from Fritz, which speeds up sim performance, in this case, for arm64: https://codereview.chromium.org/213943002/

**Comment by paul99** [comment] 2014-05-16 17:28
Based on above, I ran the 3 simulators on benchmarks test, and I see that arm32 is much faster than mips or arm64.

```
plind@swsrv5:/opt/paul/v8/gv8/benchmarks$ time ../out/arm64.release/d8 run.js
Richards: 75.1
DeltaBlue: 111
Crypto: 63.5
RayTrace: 189
EarleyBoyer: 136
RegExp: 21.5
Splay: 101
NavierStokes: 94.3
----
Score (version 7): 85.3

real    5m57.044s
user    5m56.480s
sys 0m0.070s

plind@swsrv5:/opt/paul/v8/gv8/benchmarks$ time ../out/arm.release/d8 run.js
Richards: 136
DeltaBlue: 226
Crypto: 90.0
RayTrace: 317
EarleyBoyer: 239
RegExp: 38.9
Splay: 160
NavierStokes: 124
----
Score (version 7): 142

real    3m42.641s
user    3m42.340s
sys 0m0.050s

plind@swsrv5:/opt/paul/v8/gv8/benchmarks$ time ../out/mipsel.release/d8 run.js
Richards: 96.4
DeltaBlue: 160
Crypto: 56.1
RayTrace: 222
EarleyBoyer: 155
RegExp: 26.9
Splay: 108
NavierStokes: 65.1
----
Score (version 7): 93.1

real    5m43.038s
user    5m42.530s
sys 0m0.040s
```

**Comment by paul99** [comment] 2016-01-18 19:32
Fixed by Balázs' https://codereview.chromium.org/1310883005 and some follow-ons: https://codereview.chromium.org/1314673010 , https://codereview.chromium.org/1356693002

**Closed as completed by paul99** 2016-01-18 19:32 UTC
Labels: improvement idea, pri2
