### ISSUE TITLE
Bughunting: mjsunit/regress/regress-165637 flaky fail on MIPS64 simulator

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#637] opened 2018-05-17 13:46 UTC
Link to failure on buildbot: https://v8.imgtec.com/bbv8/builders/Sim%20-%20MIPS64%20-%20Debug%20-%20edge%20-%20liftoff/builds/161/steps/Liftoff%20%28flakes%29/logs/regress-165637

**Comment by mkaric** [comment] 2018-05-23 14:49
This test has been failing occasionally in the past, discussed in issues #363 and #389. In short, the test does array slices in a loop and measures that the time required is less than 3 seconds. Recently it started failing again, more precisely since the commit 33157f3de7 (https://chromium-review.googlesource.com/c/v8/v8/+/1027855). This commit added almost 30% to the size of code that gets executed inside the loop, but this is actually not the problem.

The problem is that we are doing performance testing in debug mode which doesn't really make sense. In release mode the test runs about 25 times faster. In debug mode the 3 second time limit is too tight causing the test to fail occasionally and can be caused by small changes like adding a DCHECK to the code. Such changes affect the result of the test but this is not what the test was intended to do.

Also, this test has recently been set to skip for arm64 in commit e14ed48cb075 for similar reasons and is already set to skip for several other conditions. I propose we skip this test for mips in debug mode.

**Comment by mkaric** [comment] 2018-05-25 08:50
The test is no longer executed on buildbots in debug mode. Closing.

**Closed as completed by mkaric** 2018-05-25 08:50 UTC
