### ISSUE TITLE
Compile fails when using the mips64el.optdebug target

### ISSUE THREAD

**Issue by MIPSbkirby** [v8mips/v8mips#118] opened 2015-01-21 02:21 UTC
The "Target - MIPS64 - Debug - edge - builder" has been failing to compile since commit aeb09e6dcfbdbad68e1766a4433c992f94b129c5 (r26019).  The change made the Buildbot builder compile like the _mips64el.optdebug_ target rather than the _mips64el.debug_ target.  The errors seem to be due to the -DDEBUG flag.  When this is removed, the code compiles.  However, debug code is removed making this builder invalid.  

I've investiaged what is happening and I'm focusing on the code in _v8/src/token.h_.  The code that is failing to compile is in _v8/src/token.h_ looks like the following when it has the debug code:

```
// Returns a string corresponding to the C++ token name
// (e.g. "LT" for the token LT).
static const char* Name(Value tok) {
  do { if ((__builtin_expect(!!(!(tok < NUM_TOKENS)), 0))) { V8_Fatal(".././src/token.h", 186, "CHECK(%s) failed", "tok < NUM_TOKENS"); } } while (0);
  return name_[tok];
}
```

And, like the following when DEBUG is turned off:

```
// Returns a string corresponding to the C++ token name
// (e.g. "LT" for the token LT).
static const char* Name(Value tok) {
  ((void) 0);
  return name_[tok];
}
```

When it fails to compile, I see errors like this:

```
In file included from ././././././scanner.h:16:0,
                 from ./././././conversions-inl.h:21,
                 from ././././objects-inl.h:18,
                 from ./././v8.h:39,
                 from ././hydrogen.h:8,
                 from ./hydrogen-range-analysis.h:8,
                 from hydrogen-range-analysis.cc:5:
./././././././token.h: In member function �void v8::internal::HRangeAnalysisPhase::UpdateControlFlowRange(v8::internal::Token::Value, v8::internal::HValue*, v8::internal::HValue*)�:
./././././././token.h:187:21: error: array subscript is above array bounds [-Werror=array-bounds]
     return name_[tok];
                     ^
cc1plus: all warnings being treated as errors
```

If I turn the DEBUG flag off, then manually add the debug code to the _token.h_ I'm able to generate the error.  This implies that the debug code:

```
do { if ((__builtin_expect(!!(!(tok < NUM_TOKENS)), 0))) { V8_Fatal(".././src/token.h", 186, "CHECK(%s) failed", "tok < NUM_TOKENS"); } } while (0);
```

is broken.  But, when isolate the _token.h_ file or just the _class Token_ class, I can't reproduce the problem.

**Comment by svetozar-janjic** [comment] 2015-01-26 15:28
I have reproduce the problem with mips-linux-gnu-gcc (Sourcery CodeBench Lite 2014.05-27) 4.8.3 20140320 (prerelease) toolchain. I think that this is compiler issue, but it's also presented in Linaro ARM toolchain gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux (arm-linux-gnueabihf-cpp (crosstool-NG linaro-1.13.1-4.9-2014.09 - Linaro GCC 4.9-2014.09) 4.9.2 20140904 (prerelease)).

With this simple patch, which handle the opposite condition, build will PASS.

```
 diff --git a/src/token.h b/src/token.h
 index de8ede9..df507a1 100644
 --- a/src/token.h
 +++ b/src/token.h
 @@ -184,6 +184,9 @@ class Token {
    // (e.g. "LT" for the token LT).
    static const char* Name(Value tok) {
      DCHECK(tok < NUM_TOKENS);  // tok is unsigned
 +    if (tok >= NUM_TOKENS) {
 +       return "";
 +    }
      return name_[tok];
    }
```

I will build with other versions of MIPS toolchain to check the problem.

**Comment by paul99** [comment] 2015-01-27 02:55
I don't know if this is related, or a different issue, but I have come across this fail quite often.

Currently from building mips64el.release using gcc version 4.8.1 (Sourcery CodeBench Lite 2013.11-36) on bleeding_edge at `3937dd679bba`

```
/tmp/ccNQBGb2.s: Assembler messages:
/tmp/ccNQBGb2.s:6905: Error: invalid operands `movn $2,$4,$fcc2'
/tmp/ccNQBGb2.s:6907: Error: invalid operands `movz $18,$2,$fcc3'
/tmp/ccNQBGb2.s:7569: Error: invalid operands `movn $2,$4,$fcc2'
/tmp/ccNQBGb2.s:7571: Error: invalid operands `movz $18,$2,$fcc3'
make[1]: *** [/opt/paul/v8/g-v8/v8/out/mips64el.release/obj.target/v8_base/src/compiler/typer.o] Error 1
```

Debug build worked.

**Comment by paul99** [comment] 2015-01-27 06:08
I put new versions of the 4.9 toolchains for MIPS in Dropbox/mips/toolchains. Mti and Img (r6) versions.

**Comment by svetozar-janjic** [comment] 2015-01-27 14:06
Hi Paul,

Please provide to me access to the dropbox toolchain directory. Dusan will download it now for me, but probably I need to have access for the future?

**Comment by svetozar-janjic** [comment] 2015-01-27 16:38
We have the same build issue with new version 4.9:

  CXX(target) /home/janjic/v8/v8/out/mips.optdebug/obj.target/v8_base/src/hydrogen-redundant-phi.o
  CXX(target) /home/janjic/v8/v8/out/mips.optdebug/obj.target/v8_base/src/hydrogen-removable-simulates.o
In file included from .././src/scanner.h:16:0,
                 from .././src/conversions-inl.h:21,
                 from .././src/objects-inl.h:18,
                 from .././src/v8.h:39,
                 from .././src/hydrogen.h:8,
                 from .././src/hydrogen-range-analysis.h:8,
                 from ../src/hydrogen-range-analysis.cc:5:
.././src/token.h: In member function ‘void v8::internal::HRangeAnalysisPhase::UpdateControlFlowRange(v8::internal::Token::Value, v8::internal::HValue_, v8::internal::HValue_)’:
.././src/token.h:187:21: error: array subscript is above array bounds [-Werror=array-bounds]
     return name_[tok];
                     ^
cc1plus: all warnings being treated as errors
make[1]: **\* [/home/janjic/v8/v8/out/mips.optdebug/obj.target/v8_base/src/hydrogen-range-analysis.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
make[1]: Leaving directory `/home/janjic/v8/v8/out'
make: **\* [mips.optdebug] Error 2

mips-mti-linux-gnu-gcc (Codescape GNU Tools 2015.01-4 for MIPS Linux) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by paul99** [comment] 2015-01-27 23:12
@MIPSbkirby or @kwan0xfff can you guys try gcc 4.7.2 on mips64el target build? For me it all compiled OK, but failed to link:

```
$ make mips64el.optdebug -j1
make[1]: Entering directory `/opt/paul/v8/g-v8/v8/out'
  LINK(target) /opt/paul/v8/g-v8/v8/out/mips64el.optdebug/shell
/opt/paul/v8/g-v8/v8/out/mips64el.optdebug/obj.target/tools/gyp/libv8_libplatform.a: could not read symbols: No more archived files
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/paul/v8/g-v8/v8/out/mips64el.optdebug/shell] Error 1
make[1]: Leaving directory `/opt/paul/v8/g-v8/v8/out'
make: *** [mips64el.optdebug] Error 2
```

I used this env:

```
$ cat /home/plind/tmp/64-472-env.sh 
# Code Sourcery 2012.03-63 release
export TCPATH=/mips/arch/overflow/codesourcery/mips-linux-gnu/lite/preview/2012.09-43/Linux

export PREFIX=${TCPATH}/bin/mips-linux-gnu-

export CC=${PREFIX}gcc
export CXX=${PREFIX}g++
export AR=${PREFIX}ar
export RANLIB=${PREFIX}ranlib
export LINK=$CXX

# extras for convenience.
export OBJD=${PREFIX}objdump
export GDB=${PREFIX}gdb

# Special env flags for mips64 toolchain ldso and ld-library-path
export LDSO_PATH=${TCPATH}/mips-linux-gnu/libc/el/lib64/ld.so.1
export LD_R_PATH=${TCPATH}/mips-linux-gnu/libc/el/lib64:${TCPATH}/mips-linux-gnu/libc/el/usr/lib64
```

I had no compile errors or warnings in base v8 code, which is improvement over 4.8 and higher. (many warnings in icu code, like usual).

**Comment by paul99** [comment] 2015-01-29 17:01
@svetozar-janjic , any update on this issue?

Per the previous comment, I was able to get runnable debug code compiling with 4.7.2 (2012.09-99 release) as above, waiting until the link step fails, then changing the env to use 4.8.1 (2013.11-36), and re-running the make, which then just does the link step. I also think I just tried debug, and not optdebug.

I got code that would run, but I did not run all test suites on it. Can you please try that? If that works, might try pointing just the LINK env var at 4.8.1.

This is ugly and wrong, but it is possible this could be a short-term workaround while we determine if the compiler or the v8 source is at fault, and get them fixed. Especially if it is a toolchain issue, there will be some significant lead-time to a fix.

**Comment by kwan0xfff** [comment] 2015-01-30 00:43
Before I forget, I got basically the same result as Paul. (4.7.2 compile; 4.8.1 link)  I had a working "d8" from this process.

I found a report regarding the "could not read symbols: No more archived files" message at https://bugzilla.redhat.com/show_bug.cgi?id=915411 -- see comment 8, dated 2013-03-01. In a nutshell, it reports that thin archives are broken for 64-bit; the workaround is to use ordinary archives.  For that specific bug, "ar" was broken for 64-bit.  The report also noted an experimental patch, but the trail ends with Fedora 19 EOL; so it is not clear if this was fixed.

I confess to not being knowledgeable enough of the toolchain or our build to know if this really the problem in our case. But the "libv8_libplatform.a" file that I attempted to read with "readelf" looked suspiciously small.

**Comment by svetozar-janjic** [comment] 2015-01-30 17:46
I have compiled the code with mips64el.optdebug option (forgot to set i18nsupport=off), using 4.7.2(2012.09-99 release) to build and 4.8.1 (2013.11-36) to link. It seems that linking takes more time then usual, but probably I need to measure to compare. I have run the cctests on xlp board, result [36:44|% 100|+ 9310|-  11], mjsunit testing is running now.

With older toolchin 4.6.3 try to link, I got the same error as R. J. Dev. Kwan.

**Comment by MIPSbkirby** [comment] 2015-01-30 22:22
I narrowed down the failing command to the following:

```
/mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-4/bin/mips-mti-linux-gnu-g++ -Wall -Werror -Wno-unused-parameter -Wno-long-long -Wno-missing-field-initializers -EL -mips64r2 -mabi=64 -Wa,-mips64r2 -g -Woverloaded-virtual -O3 -Wnon-virtual-dtor -std=gnu++0x -c -o hydrogen-range-analysis.o hydrogen-range-analysis.ii
```

and showed that to Steve Ellcey in the compiler team.  He was able to duplicate the failure.  However, the latest version of GCC is able to compile this.  So, this is probably a bug in GCC that's been fixed.  Steve is looking into what commit fixed this.

Unfortunately, the latest version of GCC isn't able to build V8 either.  The error it's getting is the following:

```
make[1]: Entering directory `/export/tmp/bkirby/v8-MIPS64-debug-cross-compile-failure/mips64r2/v8/out'
  /mips/proj/build-compiler/log.2015-01-29/install-mips-mti-linux-gnu/bin/mips-mti-linux-gnu-g++ '-DV8_TARGET_ARCH_MIPS64' '-DCAN_USE_FPU_INSTRUCTIONS' '-D__mips_hard_float=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_I18N_SUPPORT' '-DGTEST_HAS_POSIX_RE=0' '-DGTEST_LANG_CXX11=0' '-DUNIT_TEST' '-DGTEST_HAS_RTTI=0' '-D_MIPS_ARCH_MIPS64R2' '-DENABLE_DISASSEMBLER' '-DV8_ENABLE_CHECKS' '-DOBJECT_PRINT' '-DVERIFY_HEAP' '-DDEBUG' '-DTRACE_MAPS' '-DENABLE_HANDLE_ZAPPING' -I../. -I../testing/gmock/include -I../testing/gtest/include -I../include  -Wall -Werror -W -Wno-unused-parameter -Wno-long-long -pthread -fno-exceptions -Wno-missing-field-initializers -EL -mhard-float -mips64r2 -mabi=64 -Wa,-mips64r2 -EL -mhard-float -mips64r2 -mabi=64 -Wa,-mips64r2 -g -Woverloaded-virtual -Woverloaded-virtual -fdata-sections -ffunction-sections -O3 -fdata-sections -ffunction-sections -O3 -Wnon-virtual-dtor -fno-rtti -std=gnu++0x -MMD -MF /export/tmp/bkirby/v8-MIPS64-debug-cross-compile-failure/mips64r2/v8/out/mips64el.optdebug/.deps//export/tmp/bkirby/v8-MIPS64-debug-cross-compile-failure/mips64r2/v8/out/mips64el.optdebug/obj.target/unittests/test/unittests/base/bits-unittest.o.d.raw  -c -o /export/tmp/bkirby/v8-MIPS64-debug-cross-compile-failure/mips64r2/v8/out/mips64el.optdebug/obj.target/unittests/test/unittests/base/bits-unittest.o ../test/unittests/base/bits-unittest.cc
In file included from .././testing/gtest/include/gtest/gtest.h:58:0,
                 from .././testing/gtest-support.h:8,
                 from ../test/unittests/base/bits-unittest.cc:9:
../test/unittests/base/bits-unittest.cc: In member function �virtual void v8::base::bits::BitsDeathTest_RoundUpToPowerOfTwo32_Test::TestBody()�:
../testing/gtest/include/gtest/internal/gtest-death-test-internal.h:192:32: error: label �gtest_label_127� used but not defined
       goto GTEST_CONCAT_TOKEN_(gtest_label_, __LINE__); \
                                ^
../testing/gtest/include/gtest/internal/gtest-internal.h:76:44: note: in definition of macro �GTEST_CONCAT_TOKEN_IMPL_
 #define GTEST_CONCAT_TOKEN_IMPL_(foo, bar) foo ## bar
                                            ^
../testing/gtest/include/gtest/internal/gtest-death-test-internal.h:192:12: note: in expansion of macro �GTEST_CONCAT_TOKEN_
       goto GTEST_CONCAT_TOKEN_(gtest_label_, __LINE__); \
            ^
../testing/gtest/include/gtest/gtest-death-test.h:169:5: note: in expansion of macro �GTEST_DEATH_TEST_
     GTEST_DEATH_TEST_(statement, predicate, regex, GTEST_FATAL_FAILURE_)
     ^
../testing/gtest/include/gtest/gtest-death-test.h:180:5: note: in expansion of macro �ASSERT_EXIT
     ASSERT_EXIT(statement, ::testing::internal::ExitedUnsuccessfully, regex)
     ^
../testing/gtest/include/gtest/gtest-death-test.h:284:5: note: in expansion of macro �ASSERT_DEATH
     ASSERT_DEATH(statement, regex)
     ^
../test/unittests/base/bits-unittest.cc:127:3: note: in expansion of macro �ASSERT_DEATH_IF_SUPPORTED
   ASSERT_DEATH_IF_SUPPORTED({ RoundUpToPowerOfTwo32(0x80000001u); },
   ^
make[1]: *** [/export/tmp/bkirby/v8-MIPS64-debug-cross-compile-failure/mips64r2/v8/out/mips64el.optdebug/obj.target/unittests/test/unittests/base/bits-unittest.o] Error 1
make[1]: Target `all' not remade because of errors.
make[1]: Leaving directory `/export/tmp/bkirby/v8-MIPS64-debug-cross-compile-failure/mips64r2/v8/out'
make: *** [mips64el.optdebug] Error 2
```

**Comment by MIPSbkirby** [comment] 2015-01-31 00:55
Steve found the bug report that fixes this compiler problem in GCC.  Here's what he told me:

> FYI: It looks like this is a bug that was in older GCC's and is now
> fixed in GCC 5.0 as of January 27, 2015.  One of the bug reports for
> this is:
> 
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56273
> 
> That shows it as being in 4.8 and fixed for 5.0.  (It doesn't say but I
> presume the bug is also in 4.9)

**Comment by MIPSbkirby** [comment] 2015-01-31 02:01
Also, adding the flag "-Wno-array-bounds" to the failing command will get the failing command to compile the C++ file.  The reason this isn't building is because warnings are errors.  I tried adding the flag with the CFLAGS variable, but the build still fails the same way.  Are there other environment variables in V8 that allow me to pass flags to the compiler?

**Comment by svetozar-janjic** [comment] 2015-02-03 17:21
Update: mjsunit results: (built with 4.7.2, linked with 4.8.1)

--- Total time: 39:48.534 ---

[40:27|% 100|+ 7775|-  65]: Done--- Total time: 40:27.876 ---

The failures are caused by :

==== C stack trace ===============================
Command: /home/janjic/v8/v8/out/mips64el.optdebug/d8 --test --random-seed=-1757448719 --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap -e TEST_FILE_NAME="/home/janjic/v8/v8/test/mjsunit/tools/profviz.js" /home/janjic/v8/v8/tools/csvparser.js /home/janjic/v8/v8/tools/splaytree.js /home/janjic/v8/v8/tools/codemap.js /home/janjic/v8/v8/tools/consarray.js /home/janjic/v8/v8/tools/profile.js /home/janjic/v8/v8/tools/profile_view.js /home/janjic/v8/v8/tools/logreader.js /home/janjic/v8/v8/tools/tickprocessor.js /home/janjic/v8/v8/tools/profviz/composer.js /home/janjic/v8/v8/test/mjsunit/mjsunit.js /home/janjic/v8/v8/test/mjsunit/tools/profviz.js
=== mjsunit/tools/profviz ===  
Warning: unknown flag --enable-slow-asserts.
Try --help for options
============ Stress 1/2 ============
#
 Fatal error in ../src/mips64/lithium-codegen-mips64.cc, line 4186
 CHECK(!instr->hydrogen()->has_transition()) failed
#

==== C stack trace ===============================
Command: /home/janjic/v8/v8/out/mips64el.optdebug/d8 --test --random-seed=-1757448719 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --allow-natives-syntax --noenable-sse2 /home/janjic/v8/v8/test/mjsunit/mjsunit.js /home/janjic/v8/v8/test/mjsunit/regress/regress-x87.js
=== mjsunit/regress/regress-x87 ===  
Warning: unknown flag --enable-slow-asserts.
Try --help for options
Warning: unknown flag --noenable-sse2.
Try --help for options
#
 Fatal error in ../src/objects-debug.cc, line 395
 CHECK((value & V8_UINT64_C(0x7FF8000000000000)) != V8_UINT64_C(0x7FF0000000000000) || (value & V8_UINT64_C(0x0007FFFFFFFFFFFF)) == V8_UINT64_C(0)) failed
#

==== C stack trace ===============================
Command: /home/janjic/v8/v8/out/mips64el.optdebug/d8 --test --random-seed=-1757448719 --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --allow-natives-syntax /home/janjic/v8/v8/test/mjsunit/mjsunit.js /home/janjic/v8/v8/test/mjsunit/regress/regress-undefined-store-keyed-fast-element.js
=== mjsunit/regress/regress-undefined-nan2 ===  
Warning: unknown flag --enable-slow-asserts.
Try --help for options
/home/janjic/v8/v8/test/mjsunit/mjsunit.js:178: Failure: expected <undefined> found <NaN>
    throw new MjsUnitAssertionError(message);
    ^
Error
    at new MjsUnitAssertionError (/home/janjic/v8/v8/test/mjsunit/mjsunit.js:31:16)
    at fail (/home/janjic/v8/v8/test/mjsunit/mjsunit.js:178:11)
    at assertEquals (/home/janjic/v8/v8/test/mjsunit/mjsunit.js:248:7)
    at /home/janjic/v8/v8/test/mjsunit/regress/regress-undefined-nan2.js:12:27
Command: /home/janjic/v8/v8/out/mips64el.optdebug/d8 --test --random-seed=-1757448719 --turbo-deoptimization --turbo-filter=\* --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap /home/janjic/v8/v8/test/mjsunit/mjsunit.js /home/janjic/v8/v8/test/mjsunit/regress/regress-undefined-nan2.js

==== C stack trace ===============================
Command: /home/janjic/v8/v8/out/mips64el.optdebug/d8 --test --random-seed=-1757448719 --nocrankshaft --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --allow-natives-syntax /home/janjic/v8/v8/test/mjsunit/mjsunit.js /home/janjic/v8/v8/test/mjsunit/regress/regress-seqstrsetchar-ex3.js
=== mjsunit/regress/regress-seqstrsetchar-ex3 ===  
Warning: unknown flag --enable-slow-asserts.
Try --help for options
#
 Fatal error in ../src/mips64/code-stubs-mips64.cc, line 2772
 CHECK(!a4.is(result_)) failed
#

**Comment by svetozar-janjic** [comment] 2015-02-03 17:24
Linaro gcc 4.8 has problem to compile arm.optdebug related to problem with third party/icu:

  CC(target) /home/janjic/v8/v8/out/arm.optdebug/obj.target/icui18n/third_party/icu/source/i18n/decContext.o
arm-linux-gnueabihf-cpp: fatal error: ‘-c’ is not a valid option to the preprocessor
compilation terminated.
make[1]: **\* [/home/janjic/v8/v8/out/arm.optdebug/obj.target/icui18n/third_party/icu/source/i18n/decContext.o] Error 1
make[1]: Leaving directory `/home/janjic/v8/v8/out'
make: **\* [arm.optdebug] Error 2

arm-linux-gnueabihf-cpp (crosstool-NG linaro-1.13.1-4.8-2013.06 - Linaro GCC 2013.06) 4.8.2 20130603 (prerelease)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by paul99** [comment] 2015-02-03 18:27
Per your previous comment / failure results, are you using recent code?

CHECK(!instr->hydrogen()->has_transition()) failed
is fixed by 1ea1141c MIPS64: Fix bugs after hole-nan value change.

CHECK(!a4.is(result_)) failed
is fixed by 54bbbdd3 MIPS64: fix wrong register use in LoadIndexedStringStub.

However, the CHECK((value & V8_UINT64_C(0x7FF8000000000000.... is not fixed yet.

**Comment by svetozar-janjic** [comment] 2015-02-05 17:35
I have use the recent code, maybe one week old. I will retest the mjsunit benchmark with the latest code, to be sure is the failures marked as fixed still there.

**Comment by svetozar-janjic** [comment] 2015-02-06 16:11
Update, latest results, V8 built with 4.7.2, linked with 4.8.1, tests executed on Netlogic board (mips64el.optdebug).

Commit: 
    commit 158a87659f02ad4d5e41d2dc19eec1f0f4ded41f
    Author: dslomov dslomov@chromium.org
    Date:   Fri Feb 6 02:34:50 2015 -0800

```
new classes: assert that constructors are not callable and rewrite 'return;'

R=arv@chromium.org
BUG=v8:3834
LOG=N

Review URL: https://codereview.chromium.org/885643004

Cr-Commit-Position: refs/heads/master@{#26483}
```

cctest: [49:21|% 100|+ 9153|-   4]
mjsunit: [58:58|% 100|+ 7809|-  79]

The log files can be found on Slack, channel "bugs".

**Comment by svetozar-janjic** [comment] 2015-02-11 17:40
I have tried to build arm.optdebug with code sourcery 4.7.3 arm toolchain, warning cause the build failure (compare signed and unsigned), with simple casting build process was continued and finished successfully.

janjic@rtrkw157-xubuntu:~/v8/v8$ make arm.optdebug
make[1]: Entering directory `/home/janjic/v8/v8/out'
  CXX(target) /home/janjic/v8/v8/out/arm.optdebug/obj.target/v8_base/src/accessors.o
In file included from .././src/v8.h:34:0,
                 from ../src/accessors.cc:5:
.././src/utils.h: In function 'void v8::internal::CopyCharsUnsigned(uint16_t*, const uint8_t*, size_t)':
.././src/utils.h:1438:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
make[1]: *** [/home/janjic/v8/v8/out/arm.optdebug/obj.target/v8_base/src/accessors.o] Error 1
make[1]: Leaving directory`/home/janjic/v8/v8/out'
make: **\* [arm.optdebug] Error 2

toolchain details:

janjic@rtrkw157-xubuntu:~/v8/v8$ $CC --version
arm-none-linux-gnueabi-cpp (Sourcery CodeBench Lite 2013.05-24) 4.7.3
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Try to get trial licence from Mentor for newer toolchain failed, but we found a way to download arm 2014.05 tar cross toolchain, this toolchain build arm.optdebug without mentioned cast (needed for 4.7.3).

janjic@rtrkw157-xubuntu:~/v8/v8$ $CC --version
arm-none-linux-gnueabi-cpp (Sourcery CodeBench Lite 2014.05-29) 4.8.3 20140320 (prerelease)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by paul99** [comment] 2015-02-18 02:02
Svetozar, please see my comments in your CL: https://codereview.chromium.org/928533002 - Jakob has given owner LGTM.

As I said there, I prefer _not_ to see the 2 comment lines repeating the same info in 3 places.

I am fine either with my initial comment making the file look like this:

```
# Target built with a Mips CXX compiler.
'cflags':
  '-EL',
  '-Wno-error=array-bounds',  # Workaround gcc bug 56273.
],
```

of

```
# Target built with a Mips CXX compiler.
'cflags':
  '-EL',
  '-Wno-error=array-bounds',  # Workaround https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56273
],
```

I guess I prefer the latter, since he allows long lines here. Please also see my other comments about wording in commit message. (You can use Edit button in CL)

You can wait for my LGTM after you update if you want, but it is also fine for @dusmil or @kilvadyb to approve this one.

**Comment by paul99** [comment] 2015-02-18 02:06
On second thought, please do wait for my LGTM. (I will try to get up early, so I can approve, and then you can tick the commit button).

The reason is we have a local patch for this in our buildbot now, and I'll need to remove that patch before this lands, since there will be a patch-conflict. I don't want the BB to be broken for multiple revisions if you land this way before I can fix that issue.

**Comment by svetozar-janjic** [comment] 2015-02-19 15:45
Please check the new patch-set!

**Comment by paul99** [comment] 2015-02-24 03:45
Landed as https://crrev.com/2bf2d4d9b6f6dbcff11e02fa636253ddd4f67a72. Thanks! 

I removed the local patches from buildbit. Closing.

**Closed as completed by paul99** 2015-02-24 03:45 UTC
