### ISSUE TITLE
Qemu mips32r6 failure: double-hi

### ISSUE THREAD

**Issue by mkaric** [v8mips/v8mips#173] opened 2015-08-07 06:07 UTC
Test: mjsunit/asm/double-hi
Flags: --stress-opt --always-opt
Command: /mips/tools/mips/swpkgs/bin/qemu-mipsel-V8-prpl-i6400-mips64r6-PRIP4-32399a2 -R 2147483648 -cpu mips32r6-generic out/Debug/d8 --test --random-seed=812368788 --stress-opt --always-opt --nohard-abort --nodead-code-elimination --nofold-constants --enable-slow-asserts --debug-code --verify-heap --allow-natives-syntax test/mjsunit/mjsunit.js test/mjsunit/asm/double-hi.js
Test fails on buildbot in debug mode only:
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20mipsr6%2Cunder%20qemu%2Cquick
Log:
https://v8.mips.com/bbv8/builders/Target%20-%20Debug%20-%20edge%20-%20mipsr6%2Cunder%20qemu%2Cquick/builds/74/steps/Check/logs/double-hi

**Comment by mkaric** [comment] 2015-08-12 15:44
This test no longer fails on buildbot. I will investigate which commit fixed the issue.

**Comment by mkaric** [comment] 2015-08-25 14:33
I discovered many tests that fail with the same error message and probably have the same root cause:

```
division-by-constant
math-floor-part1
math-floor-part2
math-floor-part3
math-floor-part4
math-round
double-lo
typedarray-slice
array-natives-elements
regress-2234
regress-94873
regress-969
regress-2261
regress-235311
switch
SharedFloat64Array
profviz
debug-suspend
atomics
math-hypot
sparse-array-reverse
math-fround
number-limits
alloc-number-debug
rotate
```

There is probably more as I didn't check all builds. None of these tests fail on mips64 or in release mode with the same message, only mips32 in debug mode. Most of these tests fail on few commits, and pass on others. Also adding minor changes to a test, like adding a print, can cause it to pass.

**Comment by mkaric** [comment] 2015-09-04 12:56
Test double-hi passes in both system and user mode qemu when v8 is built with snapshot=off. Test division-by-constant and math-floor tests still fail.

**Comment by ibogosavljevic** [comment] 2015-11-16 14:35
This issue is same as issue #177. The failure is due to qemu bug. It doesn't reproduce neither on board nor simulator. The patch from the issue #177 removes it. 
Reported to Imagination team which works supports MIPS QEMU, issue tracker id 2022
Closing issue as duplicate of #177.

**Closed as completed by ibogosavljevic** 2015-11-16 14:35 UTC
Labels: pri2
