### ISSUE TITLE
Implement instruction scheduler

### ISSUE THREAD

**Issue by lialan** [v8mips/v8mips#234] opened 2016-01-05 16:43 UTC
We should implement instruction scheduler as other architectures do. And in fact, it is pretty easy task as the core of the scheduler is already written inside src/compiler/instruction-scheduler.h(.cc).

What we need is to return a flag for each of the MIPS instruction, and there are only 4 flags so far (defined in instruction-scheduler.h).

Maybe the no-so-obvious thing is how we handle delay slots -- do the 4 flags sufficient to describe the scenario of utilizing a delay slot?

**Comment by lialan** [comment] 2016-01-20 00:34
first patch is checked in at:

https://codereview.chromium.org/1610433002

**Comment by lialan** [comment] 2016-01-27 19:33
I have implemented the instruction latency model inside the same CL.

**Comment by ibogosavljevic** [comment] 2016-12-16 09:58
Instruction scheduler is not used yet. This is duplicate of #419. CLosing issue

**Closed as completed by ibogosavljevic** 2016-12-16 09:58 UTC
