### ISSUE TITLE
testing fpxx

### ISSUE THREAD

**Issue by paul99** [v8mips/v8mips#239] opened 2016-01-19 21:32 UTC
Ivica has a CL ready for fpxx mode https://codereview.chromium.org/1586223004/, which is still in review, This is related to https://github.com/paul99/v8m-rb/issues/232

When this lands, we will need to test these modes properly, to be sure that the fix stays fixed :)

That would require having a dedicated BB builder for mips32r2 in fpxx mode, and then test it on a board running fp32 and also a board running fp64. (we need a board that can run both modes, such as Octeon-III or very likely the CI-40)

These modes can be set by configuring the kernel, but I suspect we can find some runtime-switch to set this mode. Then the BB could set the mode fp32, run the tests, set to fp64 mode and run tests again.

This would not have to be run with each commit, it could be run once a day, likely off a roll branch. 

(Extra discussion needed: fpxx does allow a dynamic mode switch: you were running fpxx code in fp64 mode, and a mips32/fp32 dynamic library is loaded late, and that forces the kernel to switch to fp32 mode for this process. Do we need to test this somewhat obscure case?)

Summary of actions needed:
1. Finish and land  https://codereview.chromium.org/1586223004/
2. Document GYP var setting for doing fpxx build
3. Find a suitable board, such as CI-40.
4. Learn how to runtime configure the kernel to use either fp32 or fp64 mode.
5. Setup BB for fpxx builds, and the two test modes for once a day testing. ( @MIPSbkirby )
6. Consider the dynamic switch scenario.

**Comment by ibogosavljevic** [comment] 2016-02-08 15:09
Here is everything you need to set up testing environment for FPXX, now that the FPXX CL is landed. To properly test FPXX binaries, we execute the same binary in two different environments, one that is FP32 and the other that is FP64. We need to test both.

Currently, we support FPXX on MIPS32R2 only, so this is the testing environment we need to set up. Please note that when compiling v8 with FPXX, it is possible that compiler sets binary to be FP32 or FP64 and not FPXX. In that case, compiled code will be FP32 or FP64 and JIT code will be FPXX. This will not have any impact on test results, but you will not be able to test the binary in both modes.

## Compilation:
- In order to compile for FPXX, you need to use a toolchain which will produce FPXX binaries. mips-mti-linux-gnu-gcc (Codescape GNU Tools 2015.01-7 for MIPS MTI Linux) 4.9.2 is tested and works correctly
- You need to have set up properly paths for dynamic linker and libraries. If not properly set, the binary will be compiled as FP32 and you cannot test in both modes. Here are the settings on my compiler:

```
ivica@rtrkw463-lin ~/src/o_main/v8 $ echo $LD_R_PATH 
/home/alex/ivica/tools/codescape-2015.01-7-mips-mti-linux-gnu/2015.01-7/sysroot/el/usr/lib:/home/alex/ivica/tools/codescape-2015.01-7-mips-mti-linux-gnu/2015.01-7/mips-mti-linux-gnu/lib/el
ivica@rtrkw463-lin ~/src/o_main/v8 $ echo $LDSO_PATH 
/home/alex/ivica/tools/codescape-2015.01-7-mips-mti-linux-gnu/2015.01-7/sysroot/el/usr/lib/ld-2.20.so
```
- You will need to export correct GYPFLAGS, here is how:

```
ivica@rtrkw463-lin ~/src/o_main/v8 $ echo $GYPFLAGS 
-Dmips_arch_variant=r2 -Dmips_fpu_mode=fpxx
```
- Compile v8 regulary. After compilation is done, make sure that the produce binary is actually FPXX. To check, please see instruction in #232. On my system, it looks like this:

```
Hex dump of section '.MIPS.abiflags':
  0x00400200 00002002 01010005 00000000 00000000 .. .............
  0x00400210 00000000 00000000                   ........

```

The eighth byte of .MIPS.abiflags section is fp_abi flag and it's value is 05. This signals that the binary is FPXX.

## Testing environment

The v8 binary needs to be tested in both environments, FP32 and FP64. Since the binary is FPXX, it should yield the same results when executed on both FP32 and FP64.
- For FP64,  we used EP6300C (CN6335p2.1-1250-AAP) with Cavium Octeon II V0.9. Linux kernel version is 4.1.0. We believe that any board with new version of linux kernel and with either FPU emulation or harware FP64 will do for testing. On these boards, v8 should be started in FP64 mode
- For FP32, we used Ingenic JZRISC V4.15  FPU V0.0 with JZ4780 (ci20). Linux kernel version is 3.18.3-ci20-1. We believe that any board with older version of linux kernel and a hardware FP32 will do. FPU emulation for FP32 is not working correctly in older kernel versions because MTHC1 and MFHC1 weren't supported until recently.

## Verifying mode in which v8 is running

To determine which FP mode v8 is using, in cpu.cc find a line containing `is_fp64_mode_ = __detect_fp64_mode();` and add a line below it `printf("FP64 mode = %d\n", is_fp64_mode_);`. Then start v8 manually by executing `v8/out/mipsel.release/d8`. You should see the FP mode in which v8 started.
Please confirm that on FP32 system the binary runs as FP32 and on FP64 system the binary runs as FP64.

**Comment by MIPSbkirby** [comment] 2016-03-22 01:26
I've built V8 following the instructions above including the printf line in the cpu.cc file.  However, it always returns "FP64 mode = 0" whether I'm on a Ci20 (Ingenic CPU) board, a Edge Router Pro (Octeon II CPU) board or a Rhino (Octeon III) board.  Shouldn't this change to "FP64 mode = 1" on one of these boards?

**Comment by ibogosavljevic** [comment] 2016-03-22 12:27
What is the kernel version on these boards?
Also, is binary really built with FPXX? What is the hex dump of MIPS.abiflags? What toolchain are you using?

**Comment by MIPSbkirby** [comment] 2016-03-22 18:38
The Rhino board (OCTEON III) is running kernel version 3.10.20.  The Ci20 board (Ingenic) is running kernel version 3.18.3.  And, the Edge Router Pro board (OCTEON II) is running kernel version 4.1.4:

```
 $ dsh -o-lroot -mmipsswbrd045 -m bbv8-rhino-board-1 -m bbv8-ci20-board-1 uname -a 
 mipsswbrd045: Linux mipsswbrd045 4.1.4 #1 SMP PREEMPT Mon Aug 3 14:22:54 PDT 2015 mips64 GNU/Linux
 bbv8-rhino-board-1: Linux mipsswbrd065 3.10.20-rt14-CavOct3-ImgTec #4 SMP Wed Jun 3 16:45:34 PDT 2015 mips64 GNU/Linux
 bbv8-ci20-board-1: Linux mipsswbrd059 3.18.3-ci20-1 #1 SMP PREEMPT Tue Sep 1 16:40:39 BST 2015 mips GNU/Linux
```

Here is the "cpu model" from /proc/cpuinfo on all the boards:

```
 $ dsh -o-lroot -mmipsswbrd045 -m bbv8-rhino-board-1 -m bbv8-ci20-board-1 grep '"cpu model"' /proc/cpuinfo 
 mipsswbrd045: cpu model         : Cavium Octeon II V0.1
 mipsswbrd045: cpu model         : Cavium Octeon II V0.1
 bbv8-ci20-board-1: cpu model            : Ingenic JZRISC V4.15  FPU V0.0
 bbv8-ci20-board-1: cpu model            : Ingenic JZRISC V4.15  FPU V0.0
 bbv8-rhino-board-1: cpu model           : Cavium Octeon III V0.2  FPU V0.0
 bbv8-rhino-board-1: cpu model           : Cavium Octeon III V0.2  FPU V0.0
 bbv8-rhino-board-1: cpu model           : Cavium Octeon III V0.2  FPU V0.0
 bbv8-rhino-board-1: cpu model           : Cavium Octeon III V0.2  FPU V0.0
```

I followed the instructions from Issue #232 to figure out if the binary is fpxx.  Here is what I did:

```
 $ readelf -S slave/fake_slave/build/v8/out/Release/d8 | grep '\.MIPS\.abiflags'
   [ 3] .MIPS.abiflags    LOPROC+2a       00400200 000200 000018 18   A  0   0  8
 $ readelf --hex-dump=3 slave/fake_slave/build/v8/out/Release/d8 | grep -C 5 '00002002 01010005'

 Hex dump of section '.MIPS.abiflags':
   0x00400200 00002002 01010005 00000000 00000000 .. .............
   0x00400210 00000000 00000000                   ........
```

Note the last two digits of "05" in the third column of the line starting with "0x00400200" which if I'm understanding the instructions means that this is an fpxx binary.

Also, the tool chain I used to build V8 was Codescape version 2015.01-7 as recommended above.  

Here is the output of running the above d8 binaries on the above mentioned machines:

```
 $ dsh -o-lroot -mmipsswbrd045 -m bbv8-rhino-board-1 -m bbv8-ci20-board-1 "echo | $PWD/build/slave/fake_slave/build/v8/out/Release/d8"
 mipsswbrd045: FP64 mode = 0
 mipsswbrd045: V8 version 5.1.0 (candidate)
 mipsswbrd045: d8> undefined
 mipsswbrd045: d8> 
 bbv8-rhino-board-1: FP64 mode = 0
 bbv8-rhino-board-1: V8 version 5.1.0 (candidate)
 bbv8-rhino-board-1: d8> undefined
 bbv8-rhino-board-1: d8> 
 bbv8-ci20-board-1: FP64 mode = 0
 bbv8-ci20-board-1: V8 version 5.1.0 (candidate)
 bbv8-ci20-board-1: d8> undefined
 bbv8-ci20-board-1: d8> 
```

**Comment by MIPSbkirby** [comment] 2016-03-23 00:05
I talked to the compiler team and found out that the kernel needs to be 4.x (he wasn't sure about the exact version, but knew that 3 series and below kernels were too old)  Also, the libraries it links too need to be fpxx. And, I found that the mips-mti-linux-gnu-objdump command from the Codescape 2015.01-7 tool chain will show if a binary is fpxx or not.  

Checking the binary is compiled with fpxx:

```
$ ~cs_mti/bin/mips-mti-linux-gnu-objdump -p build/slave/fake_slave/build/v8/out/Release/d8 | grep '^FP ABI: '
FP ABI: Hard float (32-bit CPU, Any FPU)
```

Confirming binaries are linked against Codescape libraries:

```
 $ ssh root@mipsswbrd045 ldd $PWD/build/slave/fake_slave/build/v8/out/Release/d8
         libdl.so.2 => /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr/lib/libdl.so.2 (0x77678000)
         librt.so.1 => /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr/lib/librt.so.1 (0x77660000)
         libstdc++.so.6 => /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/mips-mti-linux-gnu/lib/el/libstdc++.so.6 (0x7754e000)
         libm.so.6 => /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr/lib/libm.so.6 (0x774c4000)
         libgcc_s.so.1 => /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/mips-mti-linux-gnu/lib/el/libgcc_s.so.1 (0x7748c000)
         libpthread.so.0 => /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr/lib/libpthread.so.0 (0x77460000)
         libc.so.6 => /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr/lib/libc.so.6 (0x772e3000)
         /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr/lib/ld-2.20.so => /lib/ld.so.1 (0x556c9000)
```

Confirming libraries are fpxx:

```
 $ ~cs_mti/bin/mips-mti-linux-gnu-objdump -p /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr
 /lib/libc.so.6 | grep '^FP ABI: '
 FP ABI: Hard float (32-bit CPU, Any FPU)
 $ ~cs_mti/bin/mips-mti-linux-gnu-objdump -p /mips/proj/build-compiler/Codescape-SDK/CentOS/x86_64/MTI/Linux-gnu/2015.01-7/sysroot/el/usr
 /lib/ld-2.20.so | grep '^FP ABI: '
 FP ABI: Hard float (32-bit CPU, Any FPU)
```

Currently the 4.x kernel doesn't run on the Rhino boards.  The Edge Router Pro doesn't have an FPU so no fp64. The ci20 does not have fir.f64 capability so also will not enter fp64 mode.  So, it doesn't look like we have any way test test fpxx in fp64 mode.

**Comment by ibogosavljevic** [comment] 2016-03-23 14:47
Yes, the version has indeed have to be > 4.0. But I believe it is 
possible to use a system with FP64 emulation. Maybe the kernel is 
compiled with FP32 emulation and it needs to be recompiled with FP64 
version, I don't know if this is a viable solution for us?

**Comment by MIPSbkirby** [comment] 2016-03-23 20:36
I've added the fpxx builders to build and test fpxx for fp32.  They are added to the "Linux Target - Special" category.  The compiler builder is building a MIPS32r2 little endian release version with fpxx.  (The "gclient runhooks" step shows GYP_DEFINES with the "mips_fpu_mode=fpxx" flag) The testsuites being run are unittest and check.  The tests suites are only being run on the Ci20 boards.  As noted above the Ci20 boards only come up as fp32.  ("FP64 mode = 0")

Since we don't have a > 4.0 kernel running on the Ci20 boards or the Rhino boards, I haven't turned on the fpxx testing for fp64.  Once we have working boards for which V8 returns "FP64 mode = 1" I will enable fp64 testing on those boards.

**Comment by MIPSbkirby** [comment] 2016-03-25 00:00
Although we don't have a > 4.0 kernel working on the Ci20 boards or the Rhino boards, the fpxx testing should work slowly on an Edge Router Pro board.  Using a 4.1.4 kernel with the MIPS_O32_FP64_SUPPORT config flag set, the d8 binary correctly reports "FP64 mode = 1":

```
$ readelf  -A build/slave/fake_slave/build/v8/out/Release/d8 | grep '^FP ABI: '
FP ABI: Hard float (32-bit CPU, Any FPU)
$ zgrep MIPS_O32_FP64_SUPPORT /proc/config.gz 
CONFIG_MIPS_O32_FP64_SUPPORT=y
$ echo | build/slave/fake_slave/build/v8/out/Release/d8
FP64 mode = 1
V8 version 5.1.0 (candidate)
d8> undefined
d8> 
```

Once the Edge Router Pro boards all get this MIPS_O32_FP64_SUPPORT flag set, I'll turn on another builder to test fpxx on them.

**Comment by ibogosavljevic** [comment] 2016-03-25 10:03
yes, this is the settings you need CONFIG_MIPS_O32_FP64_SUPPORT=y needs to be set for FP64 emulation

**Comment by MIPSbkirby** [comment] 2016-03-28 19:47
We now have kernel version 4.1.20 on all the Edge Router Pro boards:

```
$ dsh -o-lroot -mbbv8-erpro8-board-{7..15} uname -a 
bbv8-erpro8-board-12: Linux mipsswbrd052 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-10: Linux mipsswbrd050 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-11: Linux mipsswbrd051 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-15: Linux mipsswbrd058 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-14: Linux mipsswbrd057 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-7: Linux mipsswbrd027 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-8: Linux mipsswbrd028 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-9: Linux mipsswbrd029 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
bbv8-erpro8-board-13: Linux mipsswbrd056 4.1.20 #1 SMP PREEMPT Thu Mar 24 18:28:00 PDT 2016 mips64 GNU/Linux
```

The all have the MIPS_O32_FP64_SUPPORT flag set:

```
$ dsh -o-lroot -mbbv8-erpro8-board-{7..15} zgrep MIPS_O32_FP64_SUPPORT /proc/config.gz  | sort  
bbv8-erpro8-board-10: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-11: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-12: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-13: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-14: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-15: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-7: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-8: CONFIG_MIPS_O32_FP64_SUPPORT=y
bbv8-erpro8-board-9: CONFIG_MIPS_O32_FP64_SUPPORT=y
```

I've confirmed with the d8 binary with the debug printf statement that they all have "FP64 mode = 1":

```
$ dsh -o-lroot -mbbv8-erpro8-board-{7..15} "echo | $PWD/build/slave/fake_slave/build/v8/out/Release/d8 | head -1" | sort
bbv8-erpro8-board-10: FP64 mode = 1
bbv8-erpro8-board-11: FP64 mode = 1
bbv8-erpro8-board-12: FP64 mode = 1
bbv8-erpro8-board-13: FP64 mode = 1
bbv8-erpro8-board-14: FP64 mode = 1
bbv8-erpro8-board-15: FP64 mode = 1
bbv8-erpro8-board-7: FP64 mode = 1
bbv8-erpro8-board-8: FP64 mode = 1
bbv8-erpro8-board-9: FP64 mode = 1
```

So, I've turned on a new builder called "Target (1) - edge - fpxx" that tests fpxx in fp64 mode on these boards.  It's triggered off the "Target - edge - fpxx - builder" compile builder.

**Closed as completed by MIPSbkirby** 2016-03-28 19:47 UTC
Labels: pri2
