### ISSUE TITLE
mjsunit/asm/embenchen/box2d fails on MIPS64r6 (simulator and qemu)

### ISSUE THREAD

**Issue by ibogosavljevic** [v8mips/v8mips#196] opened 2015-10-12 11:59 UTC
Test mjsunit/asm/embenchen/box2d fails on both simulator and qemu on MIPS64r6 DEBUG and RELEASE, with the following error:

```
=== mjsunit/asm/embenchen/box2d ===
--- stdout ---
/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:20212: Assertion failed: a.x >= 0.0f && a.y >= 0.0f, at: Box2D/Dynamics/Contacts/b2ContactSolver.cpp,406,SolveVelocityConstraints at Error
    at stackTrace (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:1053:15)
    at ___assert_fail (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:1520:210)
    at __ZN15b2ContactSolver24SolveVelocityConstraintsEv [b2ContactSolver::SolveVelocityConstraints()] (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:11677:3)
    at __ZN8b2Island5SolveEP9b2ProfileRK10b2TimeStepRK6b2Vec2b [b2Island::Solve(bool&&*)] (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:11263:4)
    at __ZN7b2World5SolveERK10b2TimeStep [b2World::Solve(b2TimeStep?&)] (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:12091:6)
    at __ZN7b2World4StepEfii [b2World::Step(float, int, int)] (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:16279:3)
    at __Z4iterv [iter()] (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:17424:2)
    at Object._main (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:14070:3)
    at Object.callMain (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:20193:30)
    at doRun (/bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js:20250:25)
      throw e;
      ^
Command: /bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/out/Release/d8 --test --random-seed=1974618759 --nohard-abort --nodead-code-elimination --nofold-constants /bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/mjsunit.js /bbv8-slaves/mips-sim-14/build/slave/v8-linux-mips64el-sim-edge-mipsr6/build/v8/test/mjsunit/asm/embenchen/box2d.js
```

**Comment by paul99** [comment] 2015-10-13 15:09
On r6 hardware, also fails, but slightly different:

```
out/mips64el.release/d8 --test --random-seed=-680224508 --nohard-abort --nodead-code-elimination --nofold-constants test/mjsunit/mjsunit.js test/mjsunit/asm/embenchen/box2d.js
    test/mjsunit/asm/embenchen/box2d.js:20212: Assertion failed: bd->position.IsValid(), at: Box2D/Dynamics/b2Body.cpp,27,b2Body at Error
        at stackTrace (test/mjsunit/asm/embenchen/box2d.js:1053:15)
        at ___assert_fail (test/mjsunit/asm/embenchen/box2d.js:1520:210)
        at __ZN6b2BodyC2EPK9b2BodyDefP7b2World [b2Body::b2Body(b2World?**)] (test/mjsunit/asm/embenchen/box2d.js:14775:3)
        at __ZN7b2World10CreateBodyEPK9b2BodyDef [b2World::CreateBody(b2BodyDef?*)] (test/mjsunit/asm/embenchen/box2d.js:18962:3)
        at Object._main (test/mjsunit/asm/embenchen/box2d.js:14030:10)
        at Object.callMain (test/mjsunit/asm/embenchen/box2d.js:20193:30)
        at doRun (test/mjsunit/asm/embenchen/box2d.js:20250:25)
        at run (test/mjsunit/asm/embenchen/box2d.js:20265:5)
        at test/mjsunit/asm/embenchen/box2d.js:20322:1
          throw e;
          ^
```

**Comment by ilijapavlovic** [comment] 2015-10-20 14:03
The problem is located in function __ZN15b2ContactSolver24SolveVelocityConstraintsEv in box2d.js. In certain moment, the function is optimized with turbofan compiler. After turbofan optimization, following expression becomes problematical:

```
    if (!(d31 >= 0.0) | !(d34 >= 0.0)) { ... }
```

In body of `if()` statement, values for variables and expressions are printed:

```
d31 = 0
d34 = 0
(d31 >= 0.0) = false    // <--- Wrong evaluation!
(d34 >= 0.0) = false    // <--- Wrong evaluation!
!(d31 >= 0.0) = true
!(d34 >= 0.0) = true
(!(d31 >= 0.0) | !(d34 >= 0.0)) = 1
```

Additional function is created. This function takes d31 and d34 as arguments.

```
function stop_test_2(a, x, y, b) { ... }
```

This function is used in diagnostic purposes.

```
    if (counter ==1560) {
      stop_test_2(5,d31,d34,6);
    }
    if (!(d31 >= 0.0) | !(d34 >= 0.0)) {
     stop_test_2(7,d31,d34,8);
     ...
    }
```

Content of the stack on simulator before turbofan optimization:

```
sim> stack
  0x7f3cf0498748:  0x0000000600000000    25769803776 (smi 6)
  0x7f3cf0498750:  0x000000004e0aeb61     1309338465 (0x4e0aeb61 <Number: 0>)
  0x7f3cf0498758:  0x000000004e0aeb41     1309338433 (0x4e0aeb41 <Number: 0>)
  0x7f3cf0498760:  0x0000000500000000    21474836480 (smi 5)
  ...
```

Content of the stack on simulator after turbofan optimization:

```
sim> stack
  0x7fb52d32b720:  0x0000000800000000    34359738368 (smi 8)
  0x7fb52d32b728:  0x000000004e0e9ed1     1309581009 (0x4e0e9ed1 <Number: -0>)
  0x7fb52d32b730:  0x000000004e0e9ee1     1309581025 (0x4e0e9ee1 <Number: -0>)
  0x7fb52d32b738:  0x0000000700000000    30064771072 (smi 7)
  ...
```

This shows that turbofan optimization changes internal representation of d31 and d34.
Investigation continues.

**Comment by ilijapavlovic** [comment] 2015-10-21 13:00
With some older commits, the problem cannot be reproduced. The first commit, where the problem is possible to reproduce, is following:

```
commit 809f6b15be82e3b85425b5d9a45fe981d487bf43
Author: martyn.capewell <martyn.capewell@arm.com>
Date:   Thu Sep 24 04:24:23 2015 -0700

    [turbofan] Elide fp32 convert for const compares

    Reduce operations of the form f64cmp(fp32to64(x), k) to f32cmp(x, k) when k
    can be encoded as a 32-bit float.

    Review URL: https://codereview.chromium.org/1365623002

    Cr-Commit-Position: refs/heads/master@{#30909}
```

**Comment by paul99** [comment] 2015-10-26 04:44
Fixed in https://codereview.chromium.org/1425603002. Passes both simulator and umQemu. Did not yet test on HW.

Thanks for the excellent investigation, Ilija! Seeing that arm commit which enabled converting of float64 comparisons to float32 (in certain cases), and knowing this was r6-only led me to spot the bug.

The code was using the MSB, as if it needed to check sign-bit, but it did not. The bug was that the 'cmp' instruction for float32 only returns 32-bits of 1's or 0's, and the upper 32-bits are undefined. The old code checked bit 63.

I've uploaded a mips32 change -- only for consistency -- there is no bug on mips32.

Can you & @ibogosavljevic & @palfia  please do a code review?

**Comment by ilijapavlovic** [comment] 2015-10-26 15:01
Review done. Also, solution tested on simulator and Qemu (user mode) for release/debug version and it works.

**Comment by palfia** [comment] 2015-10-26 16:28
LGTM! Very nice investigation!

**Comment by paul99** [comment] 2015-10-28 15:55
Fix landed as https://crrev.com/efa752d98b471981b9bef99334cc6921f23efcf2. Closing.

**Closed as completed by paul99** 2015-10-28 15:55 UTC
